export type QType = 'mc_single' | 'mc_multiple';

export interface GQuestion {
  id: string;
  type: QType;
  question: string;
  options: string[];
  correct: number[];
  explanation: string;
}

export interface Session {
  id: number;
  title: string;
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1';
  vocabLevel: string;
  topic: string;
  description: string;
  grammarQuestions: GQuestion[];
}

export const sessions: Session[] = [
  {
    id: 1,
    title: 'Sesi 1',
    level: 'A1',
    vocabLevel: 'A1',
    topic: 'Present Simple & Articles',
    description: 'Pelajari penggunaan Present Simple dan artikel (a/an/the) dalam bahasa Inggris.',
    grammarQuestions: [
      {
        id: 's1q1', type: 'mc_single',
        question: 'She ___ to school every day.',
        options: ['go', 'goes', 'going', 'gone'],
        correct: [1],
        explanation: 'Third person singular (she/he/it) uses verb + s/es in Present Simple.',
      },
      {
        id: 's1q2', type: 'mc_single',
        question: 'They ___ football on weekends.',
        options: ['plays', 'play', 'playing', 'played'],
        correct: [1],
        explanation: 'With they/we/you/I, use the base form of the verb.',
      },
      {
        id: 's1q3', type: 'mc_single',
        question: 'He ___ not like coffee.',
        options: ['do', 'does', 'is', 'are'],
        correct: [1],
        explanation: 'Use "does" with third person singular (he/she/it) in negative sentences.',
      },
      {
        id: 's1q4', type: 'mc_single',
        question: 'My sister ___ a nurse.',
        options: ['are', 'am', 'is', 'be'],
        correct: [2],
        explanation: 'She/he/it + is.',
      },
      {
        id: 's1q5', type: 'mc_single',
        question: 'I ___ very happy today.',
        options: ['is', 'are', 'be', 'am'],
        correct: [3],
        explanation: 'I + am.',
      },
      {
        id: 's1q6', type: 'mc_multiple',
        question: 'Which sentences are grammatically CORRECT? (Choose all that apply)',
        options: [
          'She go to work every day.',
          "He doesn't like tea.",
          'They plays tennis on Sundays.',
          "We don't watch TV at night.",
        ],
        correct: [1, 3],
        explanation: '"He doesn\'t like" ✓ and "We don\'t watch" ✓ are correct. "She go" → "She goes". "They plays" → "They play".',
      },
      {
        id: 's1q7', type: 'mc_multiple',
        question: 'Which sentences use articles CORRECTLY? (Choose all that apply)',
        options: [
          'She is an engineer.',
          'I need a umbrella.',
          'An elephant is a large animal.',
          'He is a honest man.',
        ],
        correct: [0, 2],
        explanation: '"an engineer" ✓ (vowel /e/), "an elephant" ✓. "a umbrella" → "an umbrella". "a honest" → "an honest" (silent h).',
      },
    ],
  },
  {
    id: 2,
    title: 'Sesi 2',
    level: 'A1',
    vocabLevel: 'A1',
    topic: 'Past Simple & Prepositions',
    description: 'Latihan menggunakan Past Simple dan preposisi waktu dalam kalimat.',
    grammarQuestions: [
      {
        id: 's2q1', type: 'mc_single',
        question: 'She ___ to the store yesterday.',
        options: ['go', 'goes', 'went', 'gone'],
        correct: [2],
        explanation: '"went" is the irregular past tense of "go".',
      },
      {
        id: 's2q2', type: 'mc_single',
        question: 'I was born ___ 1995.',
        options: ['on', 'in', 'at', 'by'],
        correct: [1],
        explanation: 'Use "in" with years.',
      },
      {
        id: 's2q3', type: 'mc_single',
        question: 'They ___ a movie last night.',
        options: ['watch', 'watches', 'watched', 'watching'],
        correct: [2],
        explanation: 'Regular past tense: watch + ed = watched.',
      },
      {
        id: 's2q4', type: 'mc_single',
        question: 'He ___ not come to the party.',
        options: ['was', 'does', 'did', 'is'],
        correct: [2],
        explanation: 'Use "did" + not + base verb for Past Simple negatives.',
      },
      {
        id: 's2q5', type: 'mc_single',
        question: 'I met him ___ Monday morning.',
        options: ['in', 'at', 'by', 'on'],
        correct: [3],
        explanation: 'Use "on" with specific days.',
      },
      {
        id: 's2q6', type: 'mc_multiple',
        question: 'Which sentences use the CORRECT past tense? (Choose all that apply)',
        options: [
          'We was very tired after the trip.',
          'She cooked dinner last night.',
          'He goed to the market.',
          'They arrived late to the meeting.',
        ],
        correct: [1, 3],
        explanation: '"cooked" ✓ (regular) and "arrived" ✓. "We was" → "We were". "goed" → "went".',
      },
      {
        id: 's2q7', type: 'mc_multiple',
        question: 'Which prepositions are used CORRECTLY? (Choose all that apply)',
        options: [
          'She arrived at the airport on time.',
          'The meeting is in Monday.',
          'He was born in July.',
          'I will see you on the evening.',
        ],
        correct: [0, 2],
        explanation: '"at the airport" ✓ and "in July" ✓. "in Monday" → "on Monday". "on the evening" → "in the evening".',
      },
    ],
  },
  {
    id: 3,
    title: 'Sesi 3',
    level: 'A2',
    vocabLevel: 'A2',
    topic: 'Present Perfect & Comparatives',
    description: 'Pelajari Present Perfect untuk pengalaman dan kalimat perbandingan.',
    grammarQuestions: [
      {
        id: 's3q1', type: 'mc_single',
        question: 'I ___ never been to Japan.',
        options: ['has', 'have', 'had', 'am'],
        correct: [1],
        explanation: '"I" uses "have" in Present Perfect.',
      },
      {
        id: 's3q2', type: 'mc_single',
        question: 'Have you ___ sushi before?',
        options: ['eat', 'ate', 'eating', 'eaten'],
        correct: [3],
        explanation: 'Present Perfect uses the past participle: eat → eaten.',
      },
      {
        id: 's3q3', type: 'mc_single',
        question: 'Tokyo is ___ than Osaka.',
        options: ['more big', 'biggest', 'bigger', 'most big'],
        correct: [2],
        explanation: 'One-syllable adjectives add -er for comparatives: big → bigger.',
      },
      {
        id: 's3q4', type: 'mc_single',
        question: 'She has ___ here for 5 years.',
        options: ['live', 'lived', 'living', 'lives'],
        correct: [1],
        explanation: 'Present Perfect: have/has + past participle. live → lived.',
      },
      {
        id: 's3q5', type: 'mc_single',
        question: 'My new phone is ___ expensive than my old one.',
        options: ['more', 'most', 'much', 'many'],
        correct: [0],
        explanation: 'Multi-syllable adjectives use "more" for comparatives.',
      },
      {
        id: 's3q6', type: 'mc_multiple',
        question: 'Which sentences use Present Perfect CORRECTLY? (Choose all that apply)',
        options: [
          'He has lived in Tokyo since 2020.',
          'She have eaten sushi before.',
          'They have already left.',
          'I has never seen that movie.',
        ],
        correct: [0, 2],
        explanation: '"has lived" ✓ and "have already left" ✓. "She have" → "She has". "I has" → "I have".',
      },
      {
        id: 's3q7', type: 'mc_multiple',
        question: 'Which comparative sentences are CORRECT? (Choose all that apply)',
        options: [
          'She is more tall than her brother.',
          'This bag is heavier than that one.',
          'English is more difficult than Japanese.',
          'He runs more fast than me.',
        ],
        correct: [1, 2],
        explanation: '"heavier" ✓ and "more difficult" ✓. "more tall" → "taller". "more fast" → "faster".',
      },
    ],
  },
  {
    id: 4,
    title: 'Sesi 4',
    level: 'A2',
    vocabLevel: 'A2',
    topic: 'Future Forms & First Conditional',
    description: 'Latihan will, going to, dan kalimat kondisional tipe pertama.',
    grammarQuestions: [
      {
        id: 's4q1', type: 'mc_single',
        question: '"___ you help me with this?" — spontaneous request.',
        options: ['Do', 'Are', 'Will', 'Shall'],
        correct: [2],
        explanation: 'Use "will" for spontaneous decisions and requests.',
      },
      {
        id: 's4q2', type: 'mc_single',
        question: 'She is ___ to study medicine next year. (already planned)',
        options: ['go', 'gone', 'going', 'goes'],
        correct: [2],
        explanation: '"going to" is used for plans already decided.',
      },
      {
        id: 's4q3', type: 'mc_single',
        question: 'If it rains tomorrow, we ___ stay at home.',
        options: ['would', 'will', 'shall', 'are'],
        correct: [1],
        explanation: 'First conditional: If + present simple, will + base verb.',
      },
      {
        id: 's4q4', type: 'mc_single',
        question: 'I ___ help you — I promise!',
        options: ['am going to', 'going to', 'shall', 'will'],
        correct: [3],
        explanation: '"will" is used for promises.',
      },
      {
        id: 's4q5', type: 'mc_single',
        question: 'If she studies hard, she ___ pass the exam.',
        options: ['would', 'will', 'had', 'might would'],
        correct: [1],
        explanation: 'First conditional uses "will" in the result clause.',
      },
      {
        id: 's4q6', type: 'mc_multiple',
        question: 'Which sentences correctly express FUTURE plans? (Choose all that apply)',
        options: [
          'I will call you when I arrive.',
          'She going to visit her parents.',
          'They are going to move to a new house.',
          'He will be gone to the gym tomorrow.',
        ],
        correct: [0, 2],
        explanation: '"will call" ✓ and "are going to move" ✓. "She going to" → "She is going to". "will be gone" → "will go".',
      },
      {
        id: 's4q7', type: 'mc_multiple',
        question: 'Which are CORRECT first conditional sentences? (Choose all that apply)',
        options: [
          'If it will rain, we stay home.',
          'If you exercise regularly, you will feel better.',
          'If she studies, she passes.',
          'If they leave early, they will catch the train.',
        ],
        correct: [1, 3],
        explanation: '"If you exercise... you will feel" ✓ and "If they leave... they will catch" ✓. The if-clause uses Present Simple (not will).',
      },
    ],
  },
  {
    id: 5,
    title: 'Sesi 5',
    level: 'B1',
    vocabLevel: 'B1',
    topic: 'Modal Verbs & Passive Voice',
    description: 'Gunakan modal verbs dengan tepat dan pelajari kalimat pasif.',
    grammarQuestions: [
      {
        id: 's5q1', type: 'mc_single',
        question: "You ___ smoke here — it's against the rules.",
        options: ["don't have to", "needn't", "mustn't", "mightn't"],
        correct: [2],
        explanation: '"mustn\'t" = prohibition (not allowed). "don\'t have to" means not necessary but not forbidden.',
      },
      {
        id: 's5q2', type: 'mc_single',
        question: "You ___ pay for the entry — it's completely free.",
        options: ["mustn't", "can't", "don't have to", "shouldn't"],
        correct: [2],
        explanation: '"don\'t have to" = not necessary. There is no obligation.',
      },
      {
        id: 's5q3', type: 'mc_single',
        question: "He ___ be at home now — his car is parked outside.",
        options: ['can', 'may', 'must', 'should'],
        correct: [2],
        explanation: '"must" is used for logical deductions (almost certain).',
      },
      {
        id: 's5q4', type: 'mc_single',
        question: 'This building ___ in 1850.',
        options: ['built', 'has built', 'was built', 'is built'],
        correct: [2],
        explanation: 'Past passive: was/were + past participle.',
      },
      {
        id: 's5q5', type: 'mc_single',
        question: 'English ___ in many countries around the world.',
        options: ['speaks', 'is spoken', 'is speaking', 'spoke'],
        correct: [1],
        explanation: 'Present passive: is/are + past participle.',
      },
      {
        id: 's5q6', type: 'mc_multiple',
        question: 'Which modal verb sentences are CORRECT? (Choose all that apply)',
        options: [
          'She should to study harder.',
          'He must be tired after the long flight.',
          "You don't have to come if you're busy.",
          'They can to speak French.',
        ],
        correct: [1, 2],
        explanation: '"must be" ✓ and "don\'t have to" ✓. After modal verbs, use the BASE form without "to".',
      },
      {
        id: 's5q7', type: 'mc_multiple',
        question: 'Which passive sentences are CORRECT? (Choose all that apply)',
        options: [
          'The report was written by the manager.',
          'The email is being sent right now.',
          'The project has finish by the team.',
          'The windows were clean yesterday.',
        ],
        correct: [0, 1],
        explanation: '"was written" ✓ (past passive) and "is being sent" ✓ (present continuous passive). "has finish" → "has been finished". "were clean" → "were cleaned".',
      },
    ],
  },
  {
    id: 6,
    title: 'Sesi 6',
    level: 'B1',
    vocabLevel: 'B1',
    topic: 'Present Perfect Continuous & Reported Speech',
    description: 'Latihan kalimat yang sedang berlangsung dan cara melaporkan ucapan orang lain.',
    grammarQuestions: [
      {
        id: 's6q1', type: 'mc_single',
        question: "She ___ for two hours. That's why she looks tired.",
        options: ['is waiting', 'was waiting', 'has been waiting', 'waited'],
        correct: [2],
        explanation: 'Present Perfect Continuous: has/have + been + verb-ing. Used for ongoing actions from the past.',
      },
      {
        id: 's6q2', type: 'mc_single',
        question: 'How long ___ you been learning English?',
        options: ['did', 'are', 'have', 'has'],
        correct: [2],
        explanation: '"How long have you been...?" is the standard Present Perfect Continuous question.',
      },
      {
        id: 's6q3', type: 'mc_single',
        question: 'He told me that he ___ tired.',
        options: ['is', 'has', 'was', 'had'],
        correct: [2],
        explanation: 'In reported speech, present tense shifts to past: is → was.',
      },
      {
        id: 's6q4', type: 'mc_single',
        question: 'She said she ___ finish the work by Friday.',
        options: ['will', 'shall', 'would', 'can'],
        correct: [2],
        explanation: 'In reported speech, "will" shifts to "would".',
      },
      {
        id: 's6q5', type: 'mc_single',
        question: 'They ___ working on the project since January.',
        options: ['are', 'were', 'had', 'have been'],
        correct: [3],
        explanation: '"have been" + verb-ing = Present Perfect Continuous. "since January" indicates start time.',
      },
      {
        id: 's6q6', type: 'mc_multiple',
        question: 'Which reported speech sentences are CORRECT? (Choose all that apply)',
        options: [
          'He said he lives in Tokyo.',
          'She told me she was studying.',
          'They said they will come tomorrow.',
          'He said he would call me later.',
        ],
        correct: [1, 3],
        explanation: '"was studying" ✓ (present continuous → past continuous) and "would call" ✓ (will → would).',
      },
      {
        id: 's6q7', type: 'mc_multiple',
        question: 'Which sentences use Present Perfect Continuous CORRECTLY? (Choose all that apply)',
        options: [
          'She has been cooking since noon.',
          'They have been work here for years.',
          'I have been waiting for 30 minutes.',
          'He has been ate three times today.',
        ],
        correct: [0, 2],
        explanation: '"has been cooking" ✓ and "have been waiting" ✓. After "have been", always use verb+ing.',
      },
    ],
  },
  {
    id: 7,
    title: 'Sesi 7',
    level: 'B2',
    vocabLevel: 'B2',
    topic: 'Conditionals Type 2 & 3 + Relative Clauses',
    description: 'Ungkapkan situasi hipotetis dan gunakan klausa relatif.',
    grammarQuestions: [
      {
        id: 's7q1', type: 'mc_single',
        question: 'If I ___ rich, I would travel the world. (hypothetical)',
        options: ['am', 'was', 'were', 'be'],
        correct: [2],
        explanation: 'Second conditional: If + past simple (were for all persons in formal English), would + base verb.',
      },
      {
        id: 's7q2', type: 'mc_single',
        question: 'If she had studied harder, she ___ passed the exam.',
        options: ['would have', 'will have', 'had', 'would'],
        correct: [0],
        explanation: 'Third conditional: If + past perfect, would have + past participle.',
      },
      {
        id: 's7q3', type: 'mc_single',
        question: 'The woman ___ works in my office is very kind.',
        options: ['which', 'whose', 'whom', 'who'],
        correct: [3],
        explanation: '"Who" is used for people in relative clauses (subject position).',
      },
      {
        id: 's7q4', type: 'mc_single',
        question: 'The house ___ roof is red belongs to my uncle.',
        options: ['that', 'which', 'who', 'whose'],
        correct: [3],
        explanation: '"Whose" shows possession in relative clauses.',
      },
      {
        id: 's7q5', type: 'mc_single',
        question: 'If you ___ me, what would you do? (hypothetical advice)',
        options: ['are', 'was', 'be', 'were'],
        correct: [3],
        explanation: '"If you were me" — second conditional uses "were" in formal English.',
      },
      {
        id: 's7q6', type: 'mc_multiple',
        question: 'Which are CORRECT conditional sentences? (Choose all that apply)',
        options: [
          'If I had known, I would have told you.',
          'If she would study, she passed.',
          "If it weren't so cold, I would go outside.",
          'If they worked harder, they will succeed.',
        ],
        correct: [0, 2],
        explanation: '"would have told" ✓ (third conditional) and "weren\'t...would go" ✓ (second conditional).',
      },
      {
        id: 's7q7', type: 'mc_multiple',
        question: 'Which relative clauses are CORRECT? (Choose all that apply)',
        options: [
          'This is the book that changed my life.',
          'The man which I met was friendly.',
          'She is the doctor whose advice I follow.',
          'The city where I grew up is beautiful.',
        ],
        correct: [0, 2, 3],
        explanation: '"that changed" ✓, "whose advice" ✓, "where I grew up" ✓. "which" → "who" for people.',
      },
    ],
  },
  {
    id: 8,
    title: 'Sesi 8',
    level: 'B2',
    vocabLevel: 'B2',
    topic: 'Advanced Passives & Causative',
    description: 'Pelajari passive voice lanjutan dan struktur causative (have/get something done).',
    grammarQuestions: [
      {
        id: 's8q1', type: 'mc_single',
        question: 'The project ___ been completed by the team.',
        options: ['have', 'had', 'has', 'is'],
        correct: [2],
        explanation: 'Present Perfect passive: has/have + been + past participle. "The project" is singular → "has".',
      },
      {
        id: 's8q2', type: 'mc_single',
        question: 'She had her car ___ at the garage. (causative)',
        options: ['repair', 'repaired', 'repairing', 'to repair'],
        correct: [1],
        explanation: 'Causative "have": have + object + past participle.',
      },
      {
        id: 's8q3', type: 'mc_single',
        question: 'It is believed that he ___ the prize.',
        options: ['wins', 'win', 'winning', 'has won'],
        correct: [3],
        explanation: 'The reporting structure can use perfect aspect for past events.',
      },
      {
        id: 's8q4', type: 'mc_single',
        question: 'He got his hair ___ at the barbershop.',
        options: ['cut', 'cutting', 'to cut', 'cuts'],
        correct: [0],
        explanation: 'Causative "get": get + object + past participle.',
      },
      {
        id: 's8q5', type: 'mc_single',
        question: 'The results ___ announced at the ceremony tomorrow.',
        options: ['will have', 'are being', 'will be', 'be'],
        correct: [2],
        explanation: 'Future passive: will + be + past participle.',
      },
      {
        id: 's8q6', type: 'mc_multiple',
        question: 'Which causative sentences are CORRECT? (Choose all that apply)',
        options: [
          'She had her photo taken by a professional.',
          'He got his phone fix yesterday.',
          'They had the house painted last summer.',
          'I got my documents check at the office.',
        ],
        correct: [0, 2],
        explanation: '"had her photo taken" ✓ and "had the house painted" ✓. "fix" → "fixed". "check" → "checked".',
      },
      {
        id: 's8q7', type: 'mc_multiple',
        question: 'Which passive sentences are CORRECT? (Choose all that apply)',
        options: [
          'The report is being written right now.',
          'She is said to be the best in her field.',
          'The money have been transferred.',
          'It is believed that he stole the painting.',
        ],
        correct: [0, 1, 3],
        explanation: '"is being written" ✓, "is said to be" ✓, "is believed that" ✓. "The money have" → "has been transferred".',
      },
    ],
  },
  {
    id: 9,
    title: 'Sesi 9',
    level: 'B2',
    vocabLevel: 'B2',
    topic: 'Inversion & Subjunctive',
    description: 'Pelajari inversion untuk penekanan dan subjunctive dalam kalimat formal.',
    grammarQuestions: [
      {
        id: 's9q1', type: 'mc_single',
        question: 'Not only ___ she speak French, but she also speaks German.',
        options: ['is', 'has', 'did', 'does'],
        correct: [3],
        explanation: 'Inversion after "not only": auxiliary verb before subject. Present tense → "does".',
      },
      {
        id: 's9q2', type: 'mc_single',
        question: 'Rarely ___ we encounter such exceptional talent.',
        options: ['have', 'do', 'did', 'are'],
        correct: [1],
        explanation: 'Inversion with negative adverbs (rarely, never, seldom): auxiliary + subject.',
      },
      {
        id: 's9q3', type: 'mc_single',
        question: 'It is essential that every student ___ on time.',
        options: ['is', 'are', 'was', 'be'],
        correct: [3],
        explanation: 'Subjunctive mood after "it is essential/important/necessary that": use base form (be).',
      },
      {
        id: 's9q4', type: 'mc_single',
        question: 'The more you practice, ___ you become.',
        options: ['better', 'best', 'the best', 'the better'],
        correct: [3],
        explanation: '"The more..., the + comparative..." is a fixed structure.',
      },
      {
        id: 's9q5', type: 'mc_single',
        question: 'Having ___ the report, she submitted it to her manager.',
        options: ['finish', 'finishing', 'finished', 'to finish'],
        correct: [2],
        explanation: 'Perfect participle: "Having + past participle" — first action completed before second.',
      },
      {
        id: 's9q6', type: 'mc_multiple',
        question: 'Which sentences use inversion CORRECTLY? (Choose all that apply)',
        options: [
          'Never have I seen such a beautiful sunset.',
          'Rarely she visits her family.',
          'Not only did he win, but he also broke the record.',
          'Seldom do they make such mistakes.',
        ],
        correct: [0, 2, 3],
        explanation: '"Never have I seen" ✓, "Not only did he win" ✓, "Seldom do they" ✓. "Rarely she visits" → "Rarely does she visit".',
      },
      {
        id: 's9q7', type: 'mc_multiple',
        question: 'Which sentences use the subjunctive CORRECTLY? (Choose all that apply)',
        options: [
          'I suggest that he studies harder.',
          'It is important that she be informed immediately.',
          'The committee recommended that the project be cancelled.',
          'It is necessary that everyone is present.',
        ],
        correct: [1, 2],
        explanation: '"be informed" ✓ and "be cancelled" ✓. "studies" → "study" (base form). "is present" → "be present".',
      },
    ],
  },
  {
    id: 10,
    title: 'Sesi 10',
    level: 'C1',
    vocabLevel: 'C1',
    topic: 'PTE Academic Mixed Practice',
    description: 'Latihan campuran setara level PTE Academic — ujian sesungguhnya dimulai di sini!',
    grammarQuestions: [
      {
        id: 's10q1', type: 'mc_single',
        question: 'Despite ___ hard, he failed the final examination.',
        options: ['to study', 'study', 'studied', 'studying'],
        correct: [3],
        explanation: '"Despite" is a preposition, followed by a noun or verb+ing.',
      },
      {
        id: 's10q2', type: 'mc_single',
        question: 'By the time she arrives, we ___ for three hours.',
        options: ['will wait', 'are waiting', 'will be waiting', 'will have been waiting'],
        correct: [3],
        explanation: 'Future Perfect Continuous: will have been + verb-ing. Shows duration up to a future point.',
      },
      {
        id: 's10q3', type: 'mc_single',
        question: 'The CEO, together with her team, ___ the new strategy yesterday.',
        options: ['have announced', 'announce', 'has announced', 'announced'],
        correct: [3],
        explanation: '"Together with" does not affect the subject. "The CEO" (singular) + past tense → "announced".',
      },
      {
        id: 's10q4', type: 'mc_single',
        question: 'No sooner ___ he sat down than the phone rang.',
        options: ['has', 'did', 'was', 'had'],
        correct: [3],
        explanation: '"No sooner...than" uses Past Perfect + inversion: "No sooner had + subject + past participle".',
      },
      {
        id: 's10q5', type: 'mc_single',
        question: 'The phenomenon, ___ was first observed in 1950, is still not fully understood.',
        options: ['that', 'what', 'whose', 'which'],
        correct: [3],
        explanation: 'Non-defining relative clauses (with commas) use "which", not "that".',
      },
      {
        id: 's10q6', type: 'mc_multiple',
        question: 'Which sentences are GRAMMATICALLY CORRECT? (Choose all that apply)',
        options: [
          'She should have told me earlier.',
          'The data shows a clear trend.',
          'Neither the manager nor the staff was informed.',
          'He is used to work late every night.',
        ],
        correct: [0, 1],
        explanation: '"should have told" ✓ and "The data shows" ✓ (academic singular). "used to work" → "used to working".',
      },
      {
        id: 's10q7', type: 'mc_multiple',
        question: 'Which sentences reflect CORRECT academic writing style? (Choose all that apply)',
        options: [
          'It has been argued that climate change is irreversible.',
          'The results clearly showed that the hypothesis was incorrect.',
          'We can see lots of differences between the two groups.',
          'The findings suggest a significant correlation between the variables.',
        ],
        correct: [0, 1, 3],
        explanation: 'Academic style uses passive ("has been argued" ✓), past tense for results ("showed" ✓), formal vocabulary ("suggest a significant correlation" ✓). "lots of" is informal.',
      },
    ],
  },
];
