import { createClient } from '@supabase/supabase-js';
import type { VocabWord, SpacedRepetitionData, UserProgress } from '../types';

// ─── Environment Variables ────────────────────────────────────────────────────

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

const hasSupabaseConfig = Boolean(supabaseUrl && supabaseAnonKey);

if (!hasSupabaseConfig) {
  console.warn(
    '[appinggris] Supabase env vars missing — running in offline/mock mode.\n' +
    'Copy .env.example → .env.local and fill in your project credentials.'
  );
}

// Fallback placeholders so `createClient` doesn't throw at module load when
// env vars are missing (e.g. on first deploy before secrets are set). Any
// network call against these will fail, but the app shell will still render
// and `isSupabaseReady` lets calling code branch into mock/offline behavior.
const effectiveUrl = supabaseUrl || 'https://placeholder.supabase.co';
const effectiveAnonKey = supabaseAnonKey || 'placeholder-anon-key';

// ─── Typed Database Schema ────────────────────────────────────────────────────

/**
 * DB-facing vocabulary row type — mirrors the actual Supabase table columns.
 * Does NOT include legacy UI-only fields (translation, example, mastered).
 */
export interface VocabWordDB {
  id: string;
  word: string;
  pronunciation: string;
  meaning_id: string;
  meaning_en: string;
  example_sentence: string;
  example_translation: string;
  category: string;
  level: string;
  difficulty: string;
  tags: string[];
  created_at: string;
}

/** Insert payload — id and created_at are generated by the DB */
export type VocabWordInsert = Omit<VocabWordDB, 'id' | 'created_at'>;

/**
 * Supabase database type map.
 * Each key is a table name; each value has Row/Insert/Update types.
 * Expand as you add more tables.
 */
export interface Database {
  public: {
    Tables: {
      vocabulary: {
        Row: VocabWordDB;
        Insert: VocabWordInsert;
        Update: Partial<VocabWordInsert>;
      };
      spaced_repetition: {
        Row: SpacedRepetitionData & { id: string; user_id: string };
        Insert: Partial<SpacedRepetitionData> & { user_id: string; word_id: string };
        Update: Partial<Omit<SpacedRepetitionData, 'word_id'>>;
      };
      user_progress: {
        Row: UserProgress;
        Insert: Partial<UserProgress> & { user_id: string };
        Update: Partial<Omit<UserProgress, 'user_id' | 'created_at'>>;
      };
    };
  };
}

// ─── Client ───────────────────────────────────────────────────────────────────

/**
 * Typed Supabase client.
 * Import this anywhere you need database access:
 *
 *   import { supabase } from '../lib/supabase';
 *
 *   const { data, error } = await supabase
 *     .from('vocabulary')
 *     .select('*')
 *     .eq('level', 'B1');
 */
export const supabase = createClient(effectiveUrl, effectiveAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined
  }
});

// ─── Helper: check if Supabase is configured ─────────────────────────────────

/** Returns true if the Supabase client is properly configured. */
export const isSupabaseReady = hasSupabaseConfig;
