-- Oxford 5000 C1 Vocabulary Seed
-- Run in Supabase SQL Editor
-- ON CONFLICT (word) DO NOTHING to safely skip existing entries

INSERT INTO vocabulary (word, category, meaning_id, level, difficulty, tags) VALUES
('abolish', 'verb', 'menghapuskan', 'C1', 'advanced', ARRAY['oxford5000']),
('abortion', 'noun', 'aborsi', 'C1', 'advanced', ARRAY['oxford5000']),
('absence', 'noun', 'ketidakhadiran', 'C1', 'advanced', ARRAY['oxford5000']),
('absent', 'adjective', 'tidak hadir', 'C1', 'advanced', ARRAY['oxford5000']),
('absurd', 'adjective', 'tidak masuk akal', 'C1', 'advanced', ARRAY['oxford5000']),
('abundance', 'noun', 'kelimpahan', 'C1', 'advanced', ARRAY['oxford5000']),
('abuse', 'noun', 'penyalahgunaan', 'C1', 'advanced', ARRAY['oxford5000']),
('academy', 'noun', 'akademi', 'C1', 'advanced', ARRAY['oxford5000']),
('accelerate', 'verb', 'mempercepat', 'C1', 'advanced', ARRAY['oxford5000']),
('acceptance', 'noun', 'penerimaan', 'C1', 'advanced', ARRAY['oxford5000']),
('accessible', 'adjective', 'dapat diakses', 'C1', 'advanced', ARRAY['oxford5000']),
('accomplishment', 'noun', 'pencapaian', 'C1', 'advanced', ARRAY['oxford5000']),
('accountability', 'noun', 'akuntabilitas', 'C1', 'advanced', ARRAY['oxford5000']),
('activist', 'noun', 'aktivis', 'C1', 'advanced', ARRAY['oxford5000']),
('adaptation', 'noun', 'adaptasi', 'C1', 'advanced', ARRAY['oxford5000']),
('advocate', 'verb', 'menganjurkan', 'C1', 'advanced', ARRAY['oxford5000']),
('aesthetic', 'adjective', 'estetis', 'C1', 'advanced', ARRAY['oxford5000']),
('aftermath', 'noun', 'dampak', 'C1', 'advanced', ARRAY['oxford5000']),
('aggression', 'noun', 'agresi', 'C1', 'advanced', ARRAY['oxford5000']),
('alliance', 'noun', 'aliansi', 'C1', 'advanced', ARRAY['oxford5000']),
('ambassador', 'noun', 'duta besar', 'C1', 'advanced', ARRAY['oxford5000']),
('amendment', 'noun', 'amandemen', 'C1', 'advanced', ARRAY['oxford5000']),
('apparatus', 'noun', 'aparatus', 'C1', 'advanced', ARRAY['oxford5000']),
('aspiration', 'noun', 'aspirasi', 'C1', 'advanced', ARRAY['oxford5000']),
('assassination', 'noun', 'pembunuhan politik', 'C1', 'advanced', ARRAY['oxford5000']),
('asylum', 'noun', 'suaka', 'C1', 'advanced', ARRAY['oxford5000']),
('atrocity', 'noun', 'kekejaman', 'C1', 'advanced', ARRAY['oxford5000']),
('autonomy', 'noun', 'otonomi', 'C1', 'advanced', ARRAY['oxford5000']),
('ballot', 'noun', 'surat suara', 'C1', 'advanced', ARRAY['oxford5000']),
('battlefield', 'noun', 'medan perang', 'C1', 'advanced', ARRAY['oxford5000']),
('benchmark', 'noun', 'tolok ukur', 'C1', 'advanced', ARRAY['oxford5000']),
('beneficiary', 'noun', 'penerima manfaat', 'C1', 'advanced', ARRAY['oxford5000']),
('biography', 'noun', 'biografi', 'C1', 'advanced', ARRAY['oxford5000']),
('breakthrough', 'noun', 'terobosan', 'C1', 'advanced', ARRAY['oxford5000']),
('bureaucracy', 'noun', 'birokrasi', 'C1', 'advanced', ARRAY['oxford5000']),
('capability', 'noun', 'kemampuan', 'C1', 'advanced', ARRAY['oxford5000']),
('capitalism', 'noun', 'kapitalisme', 'C1', 'advanced', ARRAY['oxford5000']),
('chaos', 'noun', 'kekacauan', 'C1', 'advanced', ARRAY['oxford5000']),
('citizenship', 'noun', 'kewarganegaraan', 'C1', 'advanced', ARRAY['oxford5000']),
('civilian', 'noun', 'warga sipil', 'C1', 'advanced', ARRAY['oxford5000']),
('clarity', 'noun', 'kejelasan', 'C1', 'advanced', ARRAY['oxford5000']),
('coalition', 'noun', 'koalisi', 'C1', 'advanced', ARRAY['oxford5000']),
('collaboration', 'noun', 'kolaborasi', 'C1', 'advanced', ARRAY['oxford5000']),
('commodity', 'noun', 'komoditas', 'C1', 'advanced', ARRAY['oxford5000']),
('compassion', 'noun', 'belas kasihan', 'C1', 'advanced', ARRAY['oxford5000']),
('compensation', 'noun', 'kompensasi', 'C1', 'advanced', ARRAY['oxford5000']),
('competence', 'noun', 'kompetensi', 'C1', 'advanced', ARRAY['oxford5000']),
('complexity', 'noun', 'kompleksitas', 'C1', 'advanced', ARRAY['oxford5000']),
('compliance', 'noun', 'kepatuhan', 'C1', 'advanced', ARRAY['oxford5000']),
('confession', 'noun', 'pengakuan', 'C1', 'advanced', ARRAY['oxford5000']),
('confrontation', 'noun', 'konfrontasi', 'C1', 'advanced', ARRAY['oxford5000']),
('conscience', 'noun', 'hati nurani', 'C1', 'advanced', ARRAY['oxford5000']),
('consciousness', 'noun', 'kesadaran', 'C1', 'advanced', ARRAY['oxford5000']),
('constituency', 'noun', 'konstituen', 'C1', 'advanced', ARRAY['oxford5000']),
('constitution', 'noun', 'konstitusi', 'C1', 'advanced', ARRAY['oxford5000']),
('consultation', 'noun', 'konsultasi', 'C1', 'advanced', ARRAY['oxford5000']),
('contemplate', 'verb', 'merenungkan', 'C1', 'advanced', ARRAY['oxford5000']),
('conviction', 'noun', 'keyakinan', 'C1', 'advanced', ARRAY['oxford5000']),
('cooperate', 'verb', 'bekerja sama', 'C1', 'advanced', ARRAY['oxford5000']),
('coordinate', 'verb', 'mengkoordinasikan', 'C1', 'advanced', ARRAY['oxford5000']),
('corruption', 'noun', 'korupsi', 'C1', 'advanced', ARRAY['oxford5000']),
('credibility', 'noun', 'kredibilitas', 'C1', 'advanced', ARRAY['oxford5000']),
('cultivation', 'noun', 'pembudidayaan', 'C1', 'advanced', ARRAY['oxford5000']),
('custody', 'noun', 'hak asuh', 'C1', 'advanced', ARRAY['oxford5000']),
('declaration', 'noun', 'deklarasi', 'C1', 'advanced', ARRAY['oxford5000']),
('dedication', 'noun', 'dedikasi', 'C1', 'advanced', ARRAY['oxford5000']),
('deficit', 'noun', 'defisit', 'C1', 'advanced', ARRAY['oxford5000']),
('delegation', 'noun', 'delegasi', 'C1', 'advanced', ARRAY['oxford5000']),
('denial', 'noun', 'penolakan', 'C1', 'advanced', ARRAY['oxford5000']),
('dense', 'adjective', 'padat', 'C1', 'advanced', ARRAY['oxford5000']),
('dependence', 'noun', 'ketergantungan', 'C1', 'advanced', ARRAY['oxford5000']),
('deploy', 'verb', 'mengerahkan', 'C1', 'advanced', ARRAY['oxford5000']),
('deprive', 'verb', 'merampas', 'C1', 'advanced', ARRAY['oxford5000']),
('detention', 'noun', 'penahanan', 'C1', 'advanced', ARRAY['oxford5000']),
('deteriorate', 'verb', 'memburuk', 'C1', 'advanced', ARRAY['oxford5000']),
('devastate', 'verb', 'menghancurkan', 'C1', 'advanced', ARRAY['oxford5000']),
('diagnosis', 'noun', 'diagnosis', 'C1', 'advanced', ARRAY['oxford5000']),
('dictator', 'noun', 'diktator', 'C1', 'advanced', ARRAY['oxford5000']),
('differentiate', 'verb', 'membedakan', 'C1', 'advanced', ARRAY['oxford5000']),
('dignity', 'noun', 'martabat', 'C1', 'advanced', ARRAY['oxford5000']),
('dilemma', 'noun', 'dilema', 'C1', 'advanced', ARRAY['oxford5000']),
('diplomat', 'noun', 'diplomat', 'C1', 'advanced', ARRAY['oxford5000']),
('discrimination', 'noun', 'diskriminasi', 'C1', 'advanced', ARRAY['oxford5000']),
('dismissal', 'noun', 'pemecatan', 'C1', 'advanced', ARRAY['oxford5000']),
('disruption', 'noun', 'gangguan', 'C1', 'advanced', ARRAY['oxford5000']),
('distinction', 'noun', 'perbedaan', 'C1', 'advanced', ARRAY['oxford5000']),
('diversity', 'noun', 'keberagaman', 'C1', 'advanced', ARRAY['oxford5000']),
('doctrine', 'noun', 'doktrin', 'C1', 'advanced', ARRAY['oxford5000']),
('dominance', 'noun', 'dominasi', 'C1', 'advanced', ARRAY['oxford5000']),
('educator', 'noun', 'pendidik', 'C1', 'advanced', ARRAY['oxford5000']),
('elite', 'noun', 'elit', 'C1', 'advanced', ARRAY['oxford5000']),
('embassy', 'noun', 'kedutaan besar', 'C1', 'advanced', ARRAY['oxford5000']),
('emergence', 'noun', 'kemunculan', 'C1', 'advanced', ARRAY['oxford5000']),
('empirical', 'adjective', 'empiris', 'C1', 'advanced', ARRAY['oxford5000']),
('empower', 'verb', 'memberdayakan', 'C1', 'advanced', ARRAY['oxford5000']),
('endorse', 'verb', 'mendukung', 'C1', 'advanced', ARRAY['oxford5000']),
('enforce', 'verb', 'menegakkan', 'C1', 'advanced', ARRAY['oxford5000']),
('engagement', 'noun', 'keterlibatan', 'C1', 'advanced', ARRAY['oxford5000']),
('enterprise', 'noun', 'perusahaan', 'C1', 'advanced', ARRAY['oxford5000']),
('entity', 'noun', 'entitas', 'C1', 'advanced', ARRAY['oxford5000']),
('epidemic', 'noun', 'epidemi', 'C1', 'advanced', ARRAY['oxford5000']),
('equality', 'noun', 'kesetaraan', 'C1', 'advanced', ARRAY['oxford5000']),
('escalate', 'verb', 'meningkat', 'C1', 'advanced', ARRAY['oxford5000']),
('establishment', 'noun', 'pendirian', 'C1', 'advanced', ARRAY['oxford5000']),
('execute', 'verb', 'melaksanakan', 'C1', 'advanced', ARRAY['oxford5000']),
('exile', 'noun', 'pengasingan', 'C1', 'advanced', ARRAY['oxford5000']),
('facilitate', 'verb', 'memfasilitasi', 'C1', 'advanced', ARRAY['oxford5000']),
('fatal', 'adjective', 'mematikan', 'C1', 'advanced', ARRAY['oxford5000']),
('feat', 'noun', 'prestasi', 'C1', 'advanced', ARRAY['oxford5000']),
('flexibility', 'noun', 'fleksibilitas', 'C1', 'advanced', ARRAY['oxford5000']),
('flourish', 'verb', 'berkembang pesat', 'C1', 'advanced', ARRAY['oxford5000']),
('foreigner', 'noun', 'orang asing', 'C1', 'advanced', ARRAY['oxford5000']),
('franchise', 'noun', 'waralaba', 'C1', 'advanced', ARRAY['oxford5000']),
('frustrated', 'adjective', 'frustrasi', 'C1', 'advanced', ARRAY['oxford5000']),
('functional', 'adjective', 'fungsional', 'C1', 'advanced', ARRAY['oxford5000']),
('fundraising', 'noun', 'penggalangan dana', 'C1', 'advanced', ARRAY['oxford5000']),
('genocide', 'noun', 'genosida', 'C1', 'advanced', ARRAY['oxford5000']),
('governance', 'noun', 'tata kelola', 'C1', 'advanced', ARRAY['oxford5000']),
('guerrilla', 'noun', 'gerilya', 'C1', 'advanced', ARRAY['oxford5000']),
('harassment', 'noun', 'pelecehan', 'C1', 'advanced', ARRAY['oxford5000']),
('harmony', 'noun', 'keharmonisan', 'C1', 'advanced', ARRAY['oxford5000']),
('harvest', 'noun', 'panen', 'C1', 'advanced', ARRAY['oxford5000']),
('hatred', 'noun', 'kebencian', 'C1', 'advanced', ARRAY['oxford5000']),
('heritage', 'noun', 'warisan budaya', 'C1', 'advanced', ARRAY['oxford5000']),
('hierarchy', 'noun', 'hierarki', 'C1', 'advanced', ARRAY['oxford5000']),
('identification', 'noun', 'identifikasi', 'C1', 'advanced', ARRAY['oxford5000']),
('ideology', 'noun', 'ideologi', 'C1', 'advanced', ARRAY['oxford5000']),
('immense', 'adjective', 'sangat besar', 'C1', 'advanced', ARRAY['oxford5000']),
('imminent', 'adjective', 'segera terjadi', 'C1', 'advanced', ARRAY['oxford5000']),
('implementation', 'noun', 'implementasi', 'C1', 'advanced', ARRAY['oxford5000']),
('imprisonment', 'noun', 'pemenjaraan', 'C1', 'advanced', ARRAY['oxford5000']),
('inadequate', 'adjective', 'tidak memadai', 'C1', 'advanced', ARRAY['oxford5000']),
('inappropriate', 'adjective', 'tidak pantas', 'C1', 'advanced', ARRAY['oxford5000']),
('inclusion', 'noun', 'inklusi', 'C1', 'advanced', ARRAY['oxford5000']),
('indicator', 'noun', 'indikator', 'C1', 'advanced', ARRAY['oxford5000']),
('indigenous', 'adjective', 'pribumi', 'C1', 'advanced', ARRAY['oxford5000']),
('inequality', 'noun', 'ketidaksetaraan', 'C1', 'advanced', ARRAY['oxford5000']),
('infamous', 'adjective', 'terkenal buruk', 'C1', 'advanced', ARRAY['oxford5000']),
('influence', 'noun', 'pengaruh', 'C1', 'advanced', ARRAY['oxford5000']),
('inheritance', 'noun', 'warisan', 'C1', 'advanced', ARRAY['oxford5000']),
('initiate', 'verb', 'memulai', 'C1', 'advanced', ARRAY['oxford5000']),
('injection', 'noun', 'suntikan', 'C1', 'advanced', ARRAY['oxford5000']),
('injustice', 'noun', 'ketidakadilan', 'C1', 'advanced', ARRAY['oxford5000']),
('inmate', 'noun', 'narapidana', 'C1', 'advanced', ARRAY['oxford5000']),
('inspiration', 'noun', 'inspirasi', 'C1', 'advanced', ARRAY['oxford5000']),
('instinct', 'noun', 'naluri', 'C1', 'advanced', ARRAY['oxford5000']),
('institutional', 'adjective', 'institusional', 'C1', 'advanced', ARRAY['oxford5000']),
('integrity', 'noun', 'integritas', 'C1', 'advanced', ARRAY['oxford5000']),
('intensify', 'verb', 'mengintensifkan', 'C1', 'advanced', ARRAY['oxford5000']),
('intensity', 'noun', 'intensitas', 'C1', 'advanced', ARRAY['oxford5000']),
('interactive', 'adjective', 'interaktif', 'C1', 'advanced', ARRAY['oxford5000']),
('interfere', 'verb', 'mencampuri', 'C1', 'advanced', ARRAY['oxford5000']),
('intervention', 'noun', 'intervensi', 'C1', 'advanced', ARRAY['oxford5000']),
('intimate', 'adjective', 'intim', 'C1', 'advanced', ARRAY['oxford5000']),
('investigator', 'noun', 'penyidik', 'C1', 'advanced', ARRAY['oxford5000']),
('isolation', 'noun', 'isolasi', 'C1', 'advanced', ARRAY['oxford5000']),
('judicial', 'adjective', 'yudisial', 'C1', 'advanced', ARRAY['oxford5000']),
('jurisdiction', 'noun', 'yurisdiksi', 'C1', 'advanced', ARRAY['oxford5000']),
('justification', 'noun', 'pembenaran', 'C1', 'advanced', ARRAY['oxford5000']),
('kidnap', 'verb', 'menculik', 'C1', 'advanced', ARRAY['oxford5000']),
('kingdom', 'noun', 'kerajaan', 'C1', 'advanced', ARRAY['oxford5000']),
('landmark', 'noun', 'landmark', 'C1', 'advanced', ARRAY['oxford5000']),
('legislation', 'noun', 'undang-undang', 'C1', 'advanced', ARRAY['oxford5000']),
('legitimate', 'adjective', 'sah', 'C1', 'advanced', ARRAY['oxford5000']),
('liberty', 'noun', 'kebebasan', 'C1', 'advanced', ARRAY['oxford5000']),
('literacy', 'noun', 'melek huruf', 'C1', 'advanced', ARRAY['oxford5000']),
('loyalty', 'noun', 'loyalitas', 'C1', 'advanced', ARRAY['oxford5000']),
('mandatory', 'adjective', 'wajib', 'C1', 'advanced', ARRAY['oxford5000']),
('manipulate', 'verb', 'memanipulasi', 'C1', 'advanced', ARRAY['oxford5000']),
('massacre', 'noun', 'pembantaian', 'C1', 'advanced', ARRAY['oxford5000']),
('maximize', 'verb', 'memaksimalkan', 'C1', 'advanced', ARRAY['oxford5000']),
('medieval', 'adjective', 'abad pertengahan', 'C1', 'advanced', ARRAY['oxford5000']),
('methodology', 'noun', 'metodologi', 'C1', 'advanced', ARRAY['oxford5000']),
('migration', 'noun', 'migrasi', 'C1', 'advanced', ARRAY['oxford5000']),
('militant', 'noun', 'militan', 'C1', 'advanced', ARRAY['oxford5000']),
('militia', 'noun', 'milisi', 'C1', 'advanced', ARRAY['oxford5000']),
('ministry', 'noun', 'kementerian', 'C1', 'advanced', ARRAY['oxford5000']),
('miracle', 'noun', 'keajaiban', 'C1', 'advanced', ARRAY['oxford5000']),
('misleading', 'adjective', 'menyesatkan', 'C1', 'advanced', ARRAY['oxford5000']),
('mobility', 'noun', 'mobilitas', 'C1', 'advanced', ARRAY['oxford5000']),
('mobilize', 'verb', 'memobilisasi', 'C1', 'advanced', ARRAY['oxford5000']),
('momentum', 'noun', 'momentum', 'C1', 'advanced', ARRAY['oxford5000']),
('monopoly', 'noun', 'monopoli', 'C1', 'advanced', ARRAY['oxford5000']),
('morality', 'noun', 'moralitas', 'C1', 'advanced', ARRAY['oxford5000']),
('motive', 'noun', 'motif', 'C1', 'advanced', ARRAY['oxford5000']),
('mutual', 'adjective', 'saling', 'C1', 'advanced', ARRAY['oxford5000']),
('nationwide', 'adjective', 'nasional', 'C1', 'advanced', ARRAY['oxford5000']),
('neglect', 'verb', 'mengabaikan', 'C1', 'advanced', ARRAY['oxford5000']),
('newsletter', 'noun', 'buletin', 'C1', 'advanced', ARRAY['oxford5000']),
('notable', 'adjective', 'penting', 'C1', 'advanced', ARRAY['oxford5000']),
('notorious', 'adjective', 'terkenal buruk', 'C1', 'advanced', ARRAY['oxford5000']),
('nursery', 'noun', 'pembibitan', 'C1', 'advanced', ARRAY['oxford5000']),
('obsession', 'noun', 'obsesi', 'C1', 'advanced', ARRAY['oxford5000']),
('occurrence', 'noun', 'kejadian', 'C1', 'advanced', ARRAY['oxford5000']),
('offspring', 'noun', 'keturunan', 'C1', 'advanced', ARRAY['oxford5000']),
('operational', 'adjective', 'operasional', 'C1', 'advanced', ARRAY['oxford5000']),
('optimism', 'noun', 'optimisme', 'C1', 'advanced', ARRAY['oxford5000']),
('organizational', 'adjective', 'organisasional', 'C1', 'advanced', ARRAY['oxford5000']),
('orientation', 'noun', 'orientasi', 'C1', 'advanced', ARRAY['oxford5000']),
('originate', 'verb', 'berasal', 'C1', 'advanced', ARRAY['oxford5000']),
('outbreak', 'noun', 'wabah', 'C1', 'advanced', ARRAY['oxford5000']),
('outrage', 'noun', 'kemarahan', 'C1', 'advanced', ARRAY['oxford5000']),
('overlook', 'verb', 'mengabaikan', 'C1', 'advanced', ARRAY['oxford5000']),
('oversee', 'verb', 'mengawasi', 'C1', 'advanced', ARRAY['oxford5000']),
('overwhelm', 'verb', 'membanjiri', 'C1', 'advanced', ARRAY['oxford5000']),
('parameter', 'noun', 'parameter', 'C1', 'advanced', ARRAY['oxford5000']),
('parliamentary', 'adjective', 'parlementer', 'C1', 'advanced', ARRAY['oxford5000']),
('passive', 'adjective', 'pasif', 'C1', 'advanced', ARRAY['oxford5000']),
('patent', 'noun', 'paten', 'C1', 'advanced', ARRAY['oxford5000']),
('patrol', 'noun', 'patroli', 'C1', 'advanced', ARRAY['oxford5000']),
('peculiar', 'adjective', 'aneh', 'C1', 'advanced', ARRAY['oxford5000']),
('persist', 'verb', 'bertahan', 'C1', 'advanced', ARRAY['oxford5000']),
('personnel', 'noun', 'personel', 'C1', 'advanced', ARRAY['oxford5000']),
('petition', 'noun', 'petisi', 'C1', 'advanced', ARRAY['oxford5000']),
('philosopher', 'noun', 'filsuf', 'C1', 'advanced', ARRAY['oxford5000']),
('physician', 'noun', 'dokter', 'C1', 'advanced', ARRAY['oxford5000']),
('pioneer', 'noun', 'pelopor', 'C1', 'advanced', ARRAY['oxford5000']),
('plead', 'verb', 'memohon', 'C1', 'advanced', ARRAY['oxford5000']),
('pledge', 'noun', 'janji', 'C1', 'advanced', ARRAY['oxford5000']),
('plunge', 'verb', 'terjun', 'C1', 'advanced', ARRAY['oxford5000']),
('poll', 'noun', 'jajak pendapat', 'C1', 'advanced', ARRAY['oxford5000']),
('portfolio', 'noun', 'portofolio', 'C1', 'advanced', ARRAY['oxford5000']),
('portray', 'verb', 'menggambarkan', 'C1', 'advanced', ARRAY['oxford5000']),
('postpone', 'verb', 'menunda', 'C1', 'advanced', ARRAY['oxford5000']),
('practitioner', 'noun', 'praktisi', 'C1', 'advanced', ARRAY['oxford5000']),
('preach', 'verb', 'berkhotbah', 'C1', 'advanced', ARRAY['oxford5000']),
('precedent', 'noun', 'preseden', 'C1', 'advanced', ARRAY['oxford5000']),
('precision', 'noun', 'presisi', 'C1', 'advanced', ARRAY['oxford5000']),
('predator', 'noun', 'predator', 'C1', 'advanced', ARRAY['oxford5000']),
('predecessor', 'noun', 'pendahulu', 'C1', 'advanced', ARRAY['oxford5000']),
('predominantly', 'adverb', 'terutama', 'C1', 'advanced', ARRAY['oxford5000']),
('pregnancy', 'noun', 'kehamilan', 'C1', 'advanced', ARRAY['oxford5000']),
('prejudice', 'noun', 'prasangka', 'C1', 'advanced', ARRAY['oxford5000']),
('preliminary', 'adjective', 'pendahuluan', 'C1', 'advanced', ARRAY['oxford5000']),
('premier', 'noun', 'perdana menteri', 'C1', 'advanced', ARRAY['oxford5000']),
('premise', 'noun', 'premis', 'C1', 'advanced', ARRAY['oxford5000']),
('prescribe', 'verb', 'meresepkan', 'C1', 'advanced', ARRAY['oxford5000']),
('presidency', 'noun', 'kepresidenan', 'C1', 'advanced', ARRAY['oxford5000']),
('prestigious', 'adjective', 'bergengsi', 'C1', 'advanced', ARRAY['oxford5000']),
('prevalence', 'noun', 'prevalensi', 'C1', 'advanced', ARRAY['oxford5000']),
('prevention', 'noun', 'pencegahan', 'C1', 'advanced', ARRAY['oxford5000']),
('principal', 'adjective', 'utama', 'C1', 'advanced', ARRAY['oxford5000']),
('privatization', 'noun', 'privatisasi', 'C1', 'advanced', ARRAY['oxford5000']),
('privilege', 'noun', 'hak istimewa', 'C1', 'advanced', ARRAY['oxford5000']),
('probe', 'verb', 'menyelidiki', 'C1', 'advanced', ARRAY['oxford5000']),
('proceedings', 'noun', 'proses hukum', 'C1', 'advanced', ARRAY['oxford5000']),
('proclaim', 'verb', 'memproklamasikan', 'C1', 'advanced', ARRAY['oxford5000']),
('productive', 'adjective', 'produktif', 'C1', 'advanced', ARRAY['oxford5000']),
('productivity', 'noun', 'produktivitas', 'C1', 'advanced', ARRAY['oxford5000']),
('profitable', 'adjective', 'menguntungkan', 'C1', 'advanced', ARRAY['oxford5000']),
('profound', 'adjective', 'mendalam', 'C1', 'advanced', ARRAY['oxford5000']),
('prominent', 'adjective', 'terkemuka', 'C1', 'advanced', ARRAY['oxford5000']),
('propaganda', 'noun', 'propaganda', 'C1', 'advanced', ARRAY['oxford5000']),
('prosecute', 'verb', 'menuntut', 'C1', 'advanced', ARRAY['oxford5000']),
('prosecution', 'noun', 'penuntutan', 'C1', 'advanced', ARRAY['oxford5000']),
('prosecutor', 'noun', 'jaksa penuntut', 'C1', 'advanced', ARRAY['oxford5000']),
('prospective', 'adjective', 'calon', 'C1', 'advanced', ARRAY['oxford5000']),
('prosperity', 'noun', 'kemakmuran', 'C1', 'advanced', ARRAY['oxford5000']),
('protocol', 'noun', 'protokol', 'C1', 'advanced', ARRAY['oxford5000']),
('province', 'noun', 'provinsi', 'C1', 'advanced', ARRAY['oxford5000']),
('provision', 'noun', 'ketentuan', 'C1', 'advanced', ARRAY['oxford5000']),
('provoke', 'verb', 'memprovokasi', 'C1', 'advanced', ARRAY['oxford5000']),
('psychiatric', 'adjective', 'psikiatri', 'C1', 'advanced', ARRAY['oxford5000']),
('quota', 'noun', 'kuota', 'C1', 'advanced', ARRAY['oxford5000']),
('radical', 'adjective', 'radikal', 'C1', 'advanced', ARRAY['oxford5000']),
('rally', 'noun', 'rapat umum', 'C1', 'advanced', ARRAY['oxford5000']),
('ratio', 'noun', 'rasio', 'C1', 'advanced', ARRAY['oxford5000']),
('rational', 'adjective', 'rasional', 'C1', 'advanced', ARRAY['oxford5000']),
('realization', 'noun', 'realisasi', 'C1', 'advanced', ARRAY['oxford5000']),
('rebel', 'noun', 'pemberontak', 'C1', 'advanced', ARRAY['oxford5000']),
('rebellion', 'noun', 'pemberontakan', 'C1', 'advanced', ARRAY['oxford5000']),
('recipient', 'noun', 'penerima', 'C1', 'advanced', ARRAY['oxford5000']),
('reconstruction', 'noun', 'rekonstruksi', 'C1', 'advanced', ARRAY['oxford5000']),
('referendum', 'noun', 'referendum', 'C1', 'advanced', ARRAY['oxford5000']),
('reform', 'noun', 'reformasi', 'C1', 'advanced', ARRAY['oxford5000']),
('rehabilitation', 'noun', 'rehabilitasi', 'C1', 'advanced', ARRAY['oxford5000']),
('reign', 'noun', 'pemerintahan', 'C1', 'advanced', ARRAY['oxford5000']),
('rejection', 'noun', 'penolakan', 'C1', 'advanced', ARRAY['oxford5000']),
('relevance', 'noun', 'relevansi', 'C1', 'advanced', ARRAY['oxford5000']),
('reluctant', 'adjective', 'enggan', 'C1', 'advanced', ARRAY['oxford5000']),
('remedy', 'noun', 'obat', 'C1', 'advanced', ARRAY['oxford5000']),
('removal', 'noun', 'pengangkatan', 'C1', 'advanced', ARRAY['oxford5000']),
('renowned', 'adjective', 'terkenal', 'C1', 'advanced', ARRAY['oxford5000']),
('rental', 'noun', 'sewa', 'C1', 'advanced', ARRAY['oxford5000']),
('reportedly', 'adverb', 'dilaporkan', 'C1', 'advanced', ARRAY['oxford5000']),
('reproduction', 'noun', 'reproduksi', 'C1', 'advanced', ARRAY['oxford5000']),
('republic', 'noun', 'republik', 'C1', 'advanced', ARRAY['oxford5000']),
('reside', 'verb', 'tinggal', 'C1', 'advanced', ARRAY['oxford5000']),
('residential', 'adjective', 'perumahan', 'C1', 'advanced', ARRAY['oxford5000']),
('residue', 'noun', 'sisa', 'C1', 'advanced', ARRAY['oxford5000']),
('resignation', 'noun', 'pengunduran diri', 'C1', 'advanced', ARRAY['oxford5000']),
('resistance', 'noun', 'perlawanan', 'C1', 'advanced', ARRAY['oxford5000']),
('restoration', 'noun', 'pemulihan', 'C1', 'advanced', ARRAY['oxford5000']),
('retreat', 'noun', 'mundur', 'C1', 'advanced', ARRAY['oxford5000']),
('retrieve', 'verb', 'mengambil kembali', 'C1', 'advanced', ARRAY['oxford5000']),
('revelation', 'noun', 'wahyu', 'C1', 'advanced', ARRAY['oxford5000']),
('revenge', 'noun', 'balas dendam', 'C1', 'advanced', ARRAY['oxford5000']),
('revival', 'noun', 'kebangkitan', 'C1', 'advanced', ARRAY['oxford5000']),
('rhetoric', 'noun', 'retorika', 'C1', 'advanced', ARRAY['oxford5000']),
('riot', 'noun', 'kerusuhan', 'C1', 'advanced', ARRAY['oxford5000']),
('ritual', 'noun', 'ritual', 'C1', 'advanced', ARRAY['oxford5000']),
('robust', 'adjective', 'kuat', 'C1', 'advanced', ARRAY['oxford5000']),
('rotation', 'noun', 'rotasi', 'C1', 'advanced', ARRAY['oxford5000']),
('ruling', 'noun', 'putusan', 'C1', 'advanced', ARRAY['oxford5000']),
('rumour', 'noun', 'rumor', 'C1', 'advanced', ARRAY['oxford5000']),
('sacred', 'adjective', 'sakral', 'C1', 'advanced', ARRAY['oxford5000']),
('sacrifice', 'noun', 'pengorbanan', 'C1', 'advanced', ARRAY['oxford5000']),
('sanction', 'noun', 'sanksi', 'C1', 'advanced', ARRAY['oxford5000']),
('sceptical', 'adjective', 'skeptis', 'C1', 'advanced', ARRAY['oxford5000']),
('scrutiny', 'noun', 'pengawasan ketat', 'C1', 'advanced', ARRAY['oxford5000']),
('secular', 'adjective', 'sekuler', 'C1', 'advanced', ARRAY['oxford5000']),
('seize', 'verb', 'merebut', 'C1', 'advanced', ARRAY['oxford5000']),
('selective', 'adjective', 'selektif', 'C1', 'advanced', ARRAY['oxford5000']),
('senator', 'noun', 'senator', 'C1', 'advanced', ARRAY['oxford5000']),
('sensitivity', 'noun', 'kepekaan', 'C1', 'advanced', ARRAY['oxford5000']),
('sentiment', 'noun', 'sentimen', 'C1', 'advanced', ARRAY['oxford5000']),
('separation', 'noun', 'pemisahan', 'C1', 'advanced', ARRAY['oxford5000']),
('shareholder', 'noun', 'pemegang saham', 'C1', 'advanced', ARRAY['oxford5000']),
('shatter', 'verb', 'menghancurkan', 'C1', 'advanced', ARRAY['oxford5000']),
('shipping', 'noun', 'pengiriman', 'C1', 'advanced', ARRAY['oxford5000']),
('simulate', 'verb', 'mensimulasikan', 'C1', 'advanced', ARRAY['oxford5000']),
('simulation', 'noun', 'simulasi', 'C1', 'advanced', ARRAY['oxford5000']),
('slavery', 'noun', 'perbudakan', 'C1', 'advanced', ARRAY['oxford5000']),
('solidarity', 'noun', 'solidaritas', 'C1', 'advanced', ARRAY['oxford5000']),
('sovereignty', 'noun', 'kedaulatan', 'C1', 'advanced', ARRAY['oxford5000']),
('specialist', 'noun', 'spesialis', 'C1', 'advanced', ARRAY['oxford5000']),
('specification', 'noun', 'spesifikasi', 'C1', 'advanced', ARRAY['oxford5000']),
('spectacle', 'noun', 'tontonan', 'C1', 'advanced', ARRAY['oxford5000']),
('spectrum', 'noun', 'spektrum', 'C1', 'advanced', ARRAY['oxford5000']),
('stability', 'noun', 'stabilitas', 'C1', 'advanced', ARRAY['oxford5000']),
('statistical', 'adjective', 'statistik', 'C1', 'advanced', ARRAY['oxford5000']),
('stereotype', 'noun', 'stereotip', 'C1', 'advanced', ARRAY['oxford5000']),
('stimulus', 'noun', 'stimulus', 'C1', 'advanced', ARRAY['oxford5000']),
('storage', 'noun', 'penyimpanan', 'C1', 'advanced', ARRAY['oxford5000']),
('strategic', 'adjective', 'strategis', 'C1', 'advanced', ARRAY['oxford5000']),
('structural', 'adjective', 'struktural', 'C1', 'advanced', ARRAY['oxford5000']),
('submission', 'noun', 'pengiriman', 'C1', 'advanced', ARRAY['oxford5000']),
('subscriber', 'noun', 'pelanggan', 'C1', 'advanced', ARRAY['oxford5000']),
('subscription', 'noun', 'langganan', 'C1', 'advanced', ARRAY['oxford5000']),
('subsidy', 'noun', 'subsidi', 'C1', 'advanced', ARRAY['oxford5000']),
('substantial', 'adjective', 'substansial', 'C1', 'advanced', ARRAY['oxford5000']),
('substitute', 'noun', 'pengganti', 'C1', 'advanced', ARRAY['oxford5000']),
('subtle', 'adjective', 'halus', 'C1', 'advanced', ARRAY['oxford5000']),
('suburban', 'adjective', 'pinggiran kota', 'C1', 'advanced', ARRAY['oxford5000']),
('succession', 'noun', 'suksesi', 'C1', 'advanced', ARRAY['oxford5000']),
('successive', 'adjective', 'berturut-turut', 'C1', 'advanced', ARRAY['oxford5000']),
('suicide', 'noun', 'bunuh diri', 'C1', 'advanced', ARRAY['oxford5000']),
('summit', 'noun', 'puncak', 'C1', 'advanced', ARRAY['oxford5000']),
('superior', 'adjective', 'unggul', 'C1', 'advanced', ARRAY['oxford5000']),
('supervise', 'verb', 'mengawasi', 'C1', 'advanced', ARRAY['oxford5000']),
('supplement', 'noun', 'suplemen', 'C1', 'advanced', ARRAY['oxford5000']),
('supposedly', 'adverb', 'konon', 'C1', 'advanced', ARRAY['oxford5000']),
('suppress', 'verb', 'menekan', 'C1', 'advanced', ARRAY['oxford5000']),
('supreme', 'adjective', 'tertinggi', 'C1', 'advanced', ARRAY['oxford5000']),
('surge', 'noun', 'lonjakan', 'C1', 'advanced', ARRAY['oxford5000']),
('surveillance', 'noun', 'pengawasan', 'C1', 'advanced', ARRAY['oxford5000']),
('suspension', 'noun', 'penangguhan', 'C1', 'advanced', ARRAY['oxford5000']),
('suspicion', 'noun', 'kecurigaan', 'C1', 'advanced', ARRAY['oxford5000']),
('sustain', 'verb', 'mempertahankan', 'C1', 'advanced', ARRAY['oxford5000']),
('symbolic', 'adjective', 'simbolis', 'C1', 'advanced', ARRAY['oxford5000']),
('syndrome', 'noun', 'sindrom', 'C1', 'advanced', ARRAY['oxford5000']),
('synthesis', 'noun', 'sintesis', 'C1', 'advanced', ARRAY['oxford5000']),
('systematic', 'adjective', 'sistematis', 'C1', 'advanced', ARRAY['oxford5000']),
('tactic', 'noun', 'taktik', 'C1', 'advanced', ARRAY['oxford5000']),
('tactical', 'adjective', 'taktis', 'C1', 'advanced', ARRAY['oxford5000']),
('taxpayer', 'noun', 'wajib pajak', 'C1', 'advanced', ARRAY['oxford5000']),
('tenant', 'noun', 'penyewa', 'C1', 'advanced', ARRAY['oxford5000']),
('tenure', 'noun', 'masa jabatan', 'C1', 'advanced', ARRAY['oxford5000']),
('terminate', 'verb', 'mengakhiri', 'C1', 'advanced', ARRAY['oxford5000']),
('terrain', 'noun', 'medan', 'C1', 'advanced', ARRAY['oxford5000']),
('testify', 'verb', 'bersaksi', 'C1', 'advanced', ARRAY['oxford5000']),
('testimony', 'noun', 'kesaksian', 'C1', 'advanced', ARRAY['oxford5000']),
('theatrical', 'adjective', 'teatrikal', 'C1', 'advanced', ARRAY['oxford5000']),
('theology', 'noun', 'teologi', 'C1', 'advanced', ARRAY['oxford5000']),
('theoretical', 'adjective', 'teoritis', 'C1', 'advanced', ARRAY['oxford5000']),
('thereafter', 'adverb', 'setelah itu', 'C1', 'advanced', ARRAY['oxford5000']),
('thereby', 'adverb', 'dengan demikian', 'C1', 'advanced', ARRAY['oxford5000']),
('thoughtful', 'adjective', 'penuh pertimbangan', 'C1', 'advanced', ARRAY['oxford5000']),
('threshold', 'noun', 'ambang batas', 'C1', 'advanced', ARRAY['oxford5000']),
('thrive', 'verb', 'berkembang', 'C1', 'advanced', ARRAY['oxford5000']),
('tighten', 'verb', 'memperketat', 'C1', 'advanced', ARRAY['oxford5000']),
('timber', 'noun', 'kayu', 'C1', 'advanced', ARRAY['oxford5000']),
('tolerance', 'noun', 'toleransi', 'C1', 'advanced', ARRAY['oxford5000']),
('tolerate', 'verb', 'mentolerir', 'C1', 'advanced', ARRAY['oxford5000']),
('torture', 'noun', 'penyiksaan', 'C1', 'advanced', ARRAY['oxford5000']),
('trademark', 'noun', 'merek dagang', 'C1', 'advanced', ARRAY['oxford5000']),
('transaction', 'noun', 'transaksi', 'C1', 'advanced', ARRAY['oxford5000']),
('transcript', 'noun', 'transkrip', 'C1', 'advanced', ARRAY['oxford5000']),
('transformation', 'noun', 'transformasi', 'C1', 'advanced', ARRAY['oxford5000']),
('transmission', 'noun', 'transmisi', 'C1', 'advanced', ARRAY['oxford5000']),
('transparency', 'noun', 'transparansi', 'C1', 'advanced', ARRAY['oxford5000']),
('trauma', 'noun', 'trauma', 'C1', 'advanced', ARRAY['oxford5000']),
('treaty', 'noun', 'perjanjian', 'C1', 'advanced', ARRAY['oxford5000']),
('tremendous', 'adjective', 'luar biasa', 'C1', 'advanced', ARRAY['oxford5000']),
('tribunal', 'noun', 'pengadilan', 'C1', 'advanced', ARRAY['oxford5000']),
('tribute', 'noun', 'penghargaan', 'C1', 'advanced', ARRAY['oxford5000']),
('triumph', 'noun', 'kemenangan', 'C1', 'advanced', ARRAY['oxford5000']),
('trustee', 'noun', 'wali amanat', 'C1', 'advanced', ARRAY['oxford5000']),
('tuition', 'noun', 'biaya kuliah', 'C1', 'advanced', ARRAY['oxford5000']),
('turnout', 'noun', 'jumlah pemilih', 'C1', 'advanced', ARRAY['oxford5000']),
('undergraduate', 'noun', 'mahasiswa S1', 'C1', 'advanced', ARRAY['oxford5000']),
('underlying', 'adjective', 'mendasar', 'C1', 'advanced', ARRAY['oxford5000']),
('undermine', 'verb', 'melemahkan', 'C1', 'advanced', ARRAY['oxford5000']),
('undoubtedly', 'adverb', 'tidak diragukan', 'C1', 'advanced', ARRAY['oxford5000']),
('unify', 'verb', 'menyatukan', 'C1', 'advanced', ARRAY['oxford5000']),
('unprecedented', 'adjective', 'belum pernah terjadi', 'C1', 'advanced', ARRAY['oxford5000']),
('unveil', 'verb', 'mengungkapkan', 'C1', 'advanced', ARRAY['oxford5000']),
('upcoming', 'adjective', 'yang akan datang', 'C1', 'advanced', ARRAY['oxford5000']),
('upgrade', 'verb', 'meningkatkan', 'C1', 'advanced', ARRAY['oxford5000']),
('uphold', 'verb', 'menegakkan', 'C1', 'advanced', ARRAY['oxford5000']),
('utility', 'noun', 'utilitas', 'C1', 'advanced', ARRAY['oxford5000']),
('utilize', 'verb', 'memanfaatkan', 'C1', 'advanced', ARRAY['oxford5000']),
('vacuum', 'noun', 'kekosongan', 'C1', 'advanced', ARRAY['oxford5000']),
('validity', 'noun', 'validitas', 'C1', 'advanced', ARRAY['oxford5000']),
('vanish', 'verb', 'menghilang', 'C1', 'advanced', ARRAY['oxford5000']),
('variable', 'noun', 'variabel', 'C1', 'advanced', ARRAY['oxford5000']),
('verdict', 'noun', 'putusan', 'C1', 'advanced', ARRAY['oxford5000']),
('verify', 'verb', 'memverifikasi', 'C1', 'advanced', ARRAY['oxford5000']),
('vessel', 'noun', 'kapal', 'C1', 'advanced', ARRAY['oxford5000']),
('veteran', 'noun', 'veteran', 'C1', 'advanced', ARRAY['oxford5000']),
('viable', 'adjective', 'layak', 'C1', 'advanced', ARRAY['oxford5000']),
('vibrant', 'adjective', 'dinamis', 'C1', 'advanced', ARRAY['oxford5000']),
('violate', 'verb', 'melanggar', 'C1', 'advanced', ARRAY['oxford5000']),
('violation', 'noun', 'pelanggaran', 'C1', 'advanced', ARRAY['oxford5000']),
('virtue', 'noun', 'kebajikan', 'C1', 'advanced', ARRAY['oxford5000']),
('vocal', 'adjective', 'vokal', 'C1', 'advanced', ARRAY['oxford5000']),
('vulnerability', 'noun', 'kerentanan', 'C1', 'advanced', ARRAY['oxford5000']),
('vulnerable', 'adjective', 'rentan', 'C1', 'advanced', ARRAY['oxford5000']),
('warehouse', 'noun', 'gudang', 'C1', 'advanced', ARRAY['oxford5000']),
('warfare', 'noun', 'peperangan', 'C1', 'advanced', ARRAY['oxford5000']),
('warrant', 'noun', 'surat perintah', 'C1', 'advanced', ARRAY['oxford5000']),
('warrior', 'noun', 'pejuang', 'C1', 'advanced', ARRAY['oxford5000']),
('weaken', 'verb', 'melemahkan', 'C1', 'advanced', ARRAY['oxford5000']),
('well-being', 'noun', 'kesejahteraan', 'C1', 'advanced', ARRAY['oxford5000']),
('whilst', 'conjunction', 'sementara', 'C1', 'advanced', ARRAY['oxford5000']),
('wholly', 'adverb', 'sepenuhnya', 'C1', 'advanced', ARRAY['oxford5000']),
('widen', 'verb', 'memperluas', 'C1', 'advanced', ARRAY['oxford5000']),
('widow', 'noun', 'janda', 'C1', 'advanced', ARRAY['oxford5000']),
('willingness', 'noun', 'kesediaan', 'C1', 'advanced', ARRAY['oxford5000']),
('withdrawal', 'noun', 'penarikan', 'C1', 'advanced', ARRAY['oxford5000']),
('worship', 'noun', 'ibadah', 'C1', 'advanced', ARRAY['oxford5000']),
('worthwhile', 'adjective', 'berharga', 'C1', 'advanced', ARRAY['oxford5000']),
('worthy', 'adjective', 'layak', 'C1', 'advanced', ARRAY['oxford5000']),
('yield', 'verb', 'menghasilkan', 'C1', 'advanced', ARRAY['oxford5000']),
('youngster', 'noun', 'anak muda', 'C1', 'advanced', ARRAY['oxford5000'])
ON CONFLICT (word) DO NOTHING;
