-- Oxford 5000 B2 Words — Run di Supabase SQL Editor
-- ON CONFLICT DO NOTHING = skip kata yang sudah ada

INSERT INTO vocabulary (word, category, meaning_id, level, difficulty, tags)
VALUES
('absorb', 'verb', 'menyerap', 'B2', 'intermediate', ARRAY['oxford5000']),
('abstract', 'adjective', 'abstrak', 'B2', 'intermediate', ARRAY['oxford5000']),
('accent', 'noun', 'aksen', 'B2', 'intermediate', ARRAY['oxford5000']),
('accidentally', 'adverb', 'secara tidak sengaja', 'B2', 'intermediate', ARRAY['oxford5000']),
('accommodate', 'verb', 'mengakomodasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('accomplish', 'verb', 'mencapai', 'B2', 'intermediate', ARRAY['oxford5000']),
('accountant', 'noun', 'akuntan', 'B2', 'intermediate', ARRAY['oxford5000']),
('accuracy', 'noun', 'akurasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('accurately', 'adverb', 'dengan akurat', 'B2', 'intermediate', ARRAY['oxford5000']),
('activate', 'verb', 'mengaktifkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('addiction', 'noun', 'kecanduan', 'B2', 'intermediate', ARRAY['oxford5000']),
('additionally', 'adverb', 'selain itu', 'B2', 'intermediate', ARRAY['oxford5000']),
('adequate', 'adjective', 'memadai', 'B2', 'intermediate', ARRAY['oxford5000']),
('adequately', 'adverb', 'dengan memadai', 'B2', 'intermediate', ARRAY['oxford5000']),
('adjust', 'verb', 'menyesuaikan', 'B2', 'intermediate', ARRAY['oxford5000']),
('affordable', 'adjective', 'terjangkau', 'B2', 'intermediate', ARRAY['oxford5000']),
('agriculture', 'noun', 'pertanian', 'B2', 'intermediate', ARRAY['oxford5000']),
('alien', 'noun', 'makhluk asing', 'B2', 'intermediate', ARRAY['oxford5000']),
('alongside', 'preposition', 'di samping', 'B2', 'intermediate', ARRAY['oxford5000']),
('altogether', 'adverb', 'secara keseluruhan', 'B2', 'intermediate', ARRAY['oxford5000']),
('ambulance', 'noun', 'ambulans', 'B2', 'intermediate', ARRAY['oxford5000']),
('amusing', 'adjective', 'menghibur', 'B2', 'intermediate', ARRAY['oxford5000']),
('analyst', 'noun', 'analis', 'B2', 'intermediate', ARRAY['oxford5000']),
('ancestor', 'noun', 'leluhur', 'B2', 'intermediate', ARRAY['oxford5000']),
('animation', 'noun', 'animasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('annually', 'adverb', 'setiap tahun', 'B2', 'intermediate', ARRAY['oxford5000']),
('anticipate', 'verb', 'mengantisipasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('anxiety', 'noun', 'kecemasan', 'B2', 'intermediate', ARRAY['oxford5000']),
('apology', 'noun', 'permintaan maaf', 'B2', 'intermediate', ARRAY['oxford5000']),
('applicant', 'noun', 'pelamar', 'B2', 'intermediate', ARRAY['oxford5000']),
('appropriately', 'adverb', 'secara tepat', 'B2', 'intermediate', ARRAY['oxford5000']),
('arrow', 'noun', 'panah', 'B2', 'intermediate', ARRAY['oxford5000']),
('artwork', 'noun', 'karya seni', 'B2', 'intermediate', ARRAY['oxford5000']),
('asset', 'noun', 'aset', 'B2', 'intermediate', ARRAY['oxford5000']),
('assign', 'verb', 'menugaskan', 'B2', 'intermediate', ARRAY['oxford5000']),
('assistance', 'noun', 'bantuan', 'B2', 'intermediate', ARRAY['oxford5000']),
('assumption', 'noun', 'asumsi', 'B2', 'intermediate', ARRAY['oxford5000']),
('assure', 'verb', 'meyakinkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('astonishing', 'adjective', 'mencengangkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('attachment', 'noun', 'lampiran', 'B2', 'intermediate', ARRAY['oxford5000']),
('auction', 'noun', 'lelang', 'B2', 'intermediate', ARRAY['oxford5000']),
('automatic', 'adjective', 'otomatis', 'B2', 'intermediate', ARRAY['oxford5000']),
('automatically', 'adverb', 'secara otomatis', 'B2', 'intermediate', ARRAY['oxford5000']),
('awareness', 'noun', 'kesadaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('awkward', 'adjective', 'canggung', 'B2', 'intermediate', ARRAY['oxford5000']),
('badge', 'noun', 'lencana', 'B2', 'intermediate', ARRAY['oxford5000']),
('balanced', 'adjective', 'seimbang', 'B2', 'intermediate', ARRAY['oxford5000']),
('ballet', 'noun', 'balet', 'B2', 'intermediate', ARRAY['oxford5000']),
('balloon', 'noun', 'balon', 'B2', 'intermediate', ARRAY['oxford5000']),
('barely', 'adverb', 'hampir tidak', 'B2', 'intermediate', ARRAY['oxford5000']),
('bargain', 'noun', 'tawar menawar', 'B2', 'intermediate', ARRAY['oxford5000']),
('basement', 'noun', 'ruang bawah tanah', 'B2', 'intermediate', ARRAY['oxford5000']),
('basket', 'noun', 'keranjang', 'B2', 'intermediate', ARRAY['oxford5000']),
('beneficial', 'adjective', 'bermanfaat', 'B2', 'intermediate', ARRAY['oxford5000']),
('bias', 'noun', 'bias', 'B2', 'intermediate', ARRAY['oxford5000']),
('bid', 'noun', 'tawaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('biological', 'adjective', 'biologis', 'B2', 'intermediate', ARRAY['oxford5000']),
('blanket', 'noun', 'selimut', 'B2', 'intermediate', ARRAY['oxford5000']),
('bold', 'adjective', 'berani', 'B2', 'intermediate', ARRAY['oxford5000']),
('bombing', 'noun', 'pemboman', 'B2', 'intermediate', ARRAY['oxford5000']),
('booking', 'noun', 'pemesanan', 'B2', 'intermediate', ARRAY['oxford5000']),
('boost', 'verb', 'meningkatkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('broadcaster', 'noun', 'penyiar', 'B2', 'intermediate', ARRAY['oxford5000']),
('broadly', 'adverb', 'secara luas', 'B2', 'intermediate', ARRAY['oxford5000']),
('cabin', 'noun', 'kabin', 'B2', 'intermediate', ARRAY['oxford5000']),
('canal', 'noun', 'kanal', 'B2', 'intermediate', ARRAY['oxford5000']),
('candle', 'noun', 'lilin', 'B2', 'intermediate', ARRAY['oxford5000']),
('carbon', 'noun', 'karbon', 'B2', 'intermediate', ARRAY['oxford5000']),
('casual', 'adjective', 'santai', 'B2', 'intermediate', ARRAY['oxford5000']),
('cave', 'noun', 'gua', 'B2', 'intermediate', ARRAY['oxford5000']),
('certainty', 'noun', 'kepastian', 'B2', 'intermediate', ARRAY['oxford5000']),
('certificate', 'noun', 'sertifikat', 'B2', 'intermediate', ARRAY['oxford5000']),
('challenging', 'adjective', 'menantang', 'B2', 'intermediate', ARRAY['oxford5000']),
('championship', 'noun', 'kejuaraan', 'B2', 'intermediate', ARRAY['oxford5000']),
('charming', 'adjective', 'menawan', 'B2', 'intermediate', ARRAY['oxford5000']),
('chase', 'verb', 'mengejar', 'B2', 'intermediate', ARRAY['oxford5000']),
('cheek', 'noun', 'pipi', 'B2', 'intermediate', ARRAY['oxford5000']),
('choir', 'noun', 'paduan suara', 'B2', 'intermediate', ARRAY['oxford5000']),
('chop', 'verb', 'mencincang', 'B2', 'intermediate', ARRAY['oxford5000']),
('circuit', 'noun', 'sirkuit', 'B2', 'intermediate', ARRAY['oxford5000']),
('civilization', 'noun', 'peradaban', 'B2', 'intermediate', ARRAY['oxford5000']),
('clarify', 'verb', 'menjelaskan', 'B2', 'intermediate', ARRAY['oxford5000']),
('classify', 'verb', 'mengklasifikasikan', 'B2', 'intermediate', ARRAY['oxford5000']),
('clerk', 'noun', 'pegawai', 'B2', 'intermediate', ARRAY['oxford5000']),
('cliff', 'noun', 'tebing', 'B2', 'intermediate', ARRAY['oxford5000']),
('clinic', 'noun', 'klinik', 'B2', 'intermediate', ARRAY['oxford5000']),
('coincidence', 'noun', 'kebetulan', 'B2', 'intermediate', ARRAY['oxford5000']),
('collector', 'noun', 'kolektor', 'B2', 'intermediate', ARRAY['oxford5000']),
('colony', 'noun', 'koloni', 'B2', 'intermediate', ARRAY['oxford5000']),
('colourful', 'adjective', 'berwarna-warni', 'B2', 'intermediate', ARRAY['oxford5000']),
('commander', 'noun', 'komandan', 'B2', 'intermediate', ARRAY['oxford5000']),
('completion', 'noun', 'penyelesaian', 'B2', 'intermediate', ARRAY['oxford5000']),
('compose', 'verb', 'menyusun', 'B2', 'intermediate', ARRAY['oxford5000']),
('composer', 'noun', 'komposer', 'B2', 'intermediate', ARRAY['oxford5000']),
('compound', 'noun', 'senyawa', 'B2', 'intermediate', ARRAY['oxford5000']),
('comprehensive', 'adjective', 'menyeluruh', 'B2', 'intermediate', ARRAY['oxford5000']),
('comprise', 'verb', 'mencakup', 'B2', 'intermediate', ARRAY['oxford5000']),
('compulsory', 'adjective', 'wajib', 'B2', 'intermediate', ARRAY['oxford5000']),
('confess', 'verb', 'mengaku', 'B2', 'intermediate', ARRAY['oxford5000']),
('confusion', 'noun', 'kebingungan', 'B2', 'intermediate', ARRAY['oxford5000']),
('consequently', 'adverb', 'akibatnya', 'B2', 'intermediate', ARRAY['oxford5000']),
('conservation', 'noun', 'konservasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('considerable', 'adjective', 'cukup besar', 'B2', 'intermediate', ARRAY['oxford5000']),
('considerably', 'adverb', 'secara signifikan', 'B2', 'intermediate', ARRAY['oxford5000']),
('consistently', 'adverb', 'secara konsisten', 'B2', 'intermediate', ARRAY['oxford5000']),
('conspiracy', 'noun', 'konspirasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('consult', 'verb', 'berkonsultasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('consultant', 'noun', 'konsultan', 'B2', 'intermediate', ARRAY['oxford5000']),
('consumption', 'noun', 'konsumsi', 'B2', 'intermediate', ARRAY['oxford5000']),
('controversial', 'adjective', 'kontroversial', 'B2', 'intermediate', ARRAY['oxford5000']),
('controversy', 'noun', 'kontroversi', 'B2', 'intermediate', ARRAY['oxford5000']),
('convenience', 'noun', 'kenyamanan', 'B2', 'intermediate', ARRAY['oxford5000']),
('convention', 'noun', 'konvensi', 'B2', 'intermediate', ARRAY['oxford5000']),
('conventional', 'adjective', 'konvensional', 'B2', 'intermediate', ARRAY['oxford5000']),
('convey', 'verb', 'menyampaikan', 'B2', 'intermediate', ARRAY['oxford5000']),
('convincing', 'adjective', 'meyakinkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('cope', 'verb', 'mengatasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('corporation', 'noun', 'korporasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('corridor', 'noun', 'koridor', 'B2', 'intermediate', ARRAY['oxford5000']),
('coverage', 'noun', 'cakupan', 'B2', 'intermediate', ARRAY['oxford5000']),
('craft', 'noun', 'kerajinan', 'B2', 'intermediate', ARRAY['oxford5000']),
('creativity', 'noun', 'kreativitas', 'B2', 'intermediate', ARRAY['oxford5000']),
('critically', 'adverb', 'secara kritis', 'B2', 'intermediate', ARRAY['oxford5000']),
('cruise', 'noun', 'kapal pesiar', 'B2', 'intermediate', ARRAY['oxford5000']),
('curious', 'adjective', 'penasaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('curriculum', 'noun', 'kurikulum', 'B2', 'intermediate', ARRAY['oxford5000']),
('dairy', 'noun', 'perusahaan susu', 'B2', 'intermediate', ARRAY['oxford5000']),
('darkness', 'noun', 'kegelapan', 'B2', 'intermediate', ARRAY['oxford5000']),
('database', 'noun', 'basis data', 'B2', 'intermediate', ARRAY['oxford5000']),
('deadline', 'noun', 'batas waktu', 'B2', 'intermediate', ARRAY['oxford5000']),
('deadly', 'adjective', 'mematikan', 'B2', 'intermediate', ARRAY['oxford5000']),
('dealer', 'noun', 'pedagang', 'B2', 'intermediate', ARRAY['oxford5000']),
('defender', 'noun', 'pembela', 'B2', 'intermediate', ARRAY['oxford5000']),
('delete', 'verb', 'menghapus', 'B2', 'intermediate', ARRAY['oxford5000']),
('democracy', 'noun', 'demokrasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('democratic', 'adjective', 'demokratis', 'B2', 'intermediate', ARRAY['oxford5000']),
('demonstration', 'noun', 'demonstrasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('depart', 'verb', 'berangkat', 'B2', 'intermediate', ARRAY['oxford5000']),
('dependent', 'adjective', 'bergantung', 'B2', 'intermediate', ARRAY['oxford5000']),
('deposit', 'noun', 'setoran', 'B2', 'intermediate', ARRAY['oxford5000']),
('depression', 'noun', 'depresi', 'B2', 'intermediate', ARRAY['oxford5000']),
('derive', 'verb', 'berasal', 'B2', 'intermediate', ARRAY['oxford5000']),
('desperately', 'adverb', 'dengan putus asa', 'B2', 'intermediate', ARRAY['oxford5000']),
('destruction', 'noun', 'kehancuran', 'B2', 'intermediate', ARRAY['oxford5000']),
('determination', 'noun', 'tekad', 'B2', 'intermediate', ARRAY['oxford5000']),
('devote', 'verb', 'mengabdikan', 'B2', 'intermediate', ARRAY['oxford5000']),
('differ', 'verb', 'berbeda', 'B2', 'intermediate', ARRAY['oxford5000']),
('disability', 'noun', 'disabilitas', 'B2', 'intermediate', ARRAY['oxford5000']),
('disabled', 'adjective', 'penyandang disabilitas', 'B2', 'intermediate', ARRAY['oxford5000']),
('disagreement', 'noun', 'ketidaksepakatan', 'B2', 'intermediate', ARRAY['oxford5000']),
('disappoint', 'verb', 'mengecewakan', 'B2', 'intermediate', ARRAY['oxford5000']),
('disappointment', 'noun', 'kekecewaan', 'B2', 'intermediate', ARRAY['oxford5000']),
('discourage', 'verb', 'melemahkan semangat', 'B2', 'intermediate', ARRAY['oxford5000']),
('disorder', 'noun', 'gangguan', 'B2', 'intermediate', ARRAY['oxford5000']),
('distant', 'adjective', 'jauh', 'B2', 'intermediate', ARRAY['oxford5000']),
('distinct', 'adjective', 'berbeda', 'B2', 'intermediate', ARRAY['oxford5000']),
('distinguish', 'verb', 'membedakan', 'B2', 'intermediate', ARRAY['oxford5000']),
('distract', 'verb', 'mengalihkan perhatian', 'B2', 'intermediate', ARRAY['oxford5000']),
('disturb', 'verb', 'mengganggu', 'B2', 'intermediate', ARRAY['oxford5000']),
('diverse', 'adjective', 'beragam', 'B2', 'intermediate', ARRAY['oxford5000']),
('diversity', 'noun', 'keberagaman', 'B2', 'intermediate', ARRAY['oxford5000']),
('divorce', 'noun', 'perceraian', 'B2', 'intermediate', ARRAY['oxford5000']),
('dominant', 'adjective', 'dominan', 'B2', 'intermediate', ARRAY['oxford5000']),
('donation', 'noun', 'donasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('downtown', 'noun', 'pusat kota', 'B2', 'intermediate', ARRAY['oxford5000']),
('dramatically', 'adverb', 'secara dramatis', 'B2', 'intermediate', ARRAY['oxford5000']),
('drought', 'noun', 'kekeringan', 'B2', 'intermediate', ARRAY['oxford5000']),
('dull', 'adjective', 'membosankan', 'B2', 'intermediate', ARRAY['oxford5000']),
('duration', 'noun', 'durasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('dynamic', 'adjective', 'dinamis', 'B2', 'intermediate', ARRAY['oxford5000']),
('economics', 'noun', 'ilmu ekonomi', 'B2', 'intermediate', ARRAY['oxford5000']),
('economist', 'noun', 'ekonom', 'B2', 'intermediate', ARRAY['oxford5000']),
('efficiently', 'adverb', 'secara efisien', 'B2', 'intermediate', ARRAY['oxford5000']),
('elbow', 'noun', 'siku', 'B2', 'intermediate', ARRAY['oxford5000']),
('electronics', 'noun', 'elektronik', 'B2', 'intermediate', ARRAY['oxford5000']),
('elegant', 'adjective', 'elegan', 'B2', 'intermediate', ARRAY['oxford5000']),
('elementary', 'adjective', 'dasar', 'B2', 'intermediate', ARRAY['oxford5000']),
('eliminate', 'verb', 'menghilangkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('embrace', 'verb', 'merangkul', 'B2', 'intermediate', ARRAY['oxford5000']),
('emission', 'noun', 'emisi', 'B2', 'intermediate', ARRAY['oxford5000']),
('emotionally', 'adverb', 'secara emosional', 'B2', 'intermediate', ARRAY['oxford5000']),
('empire', 'noun', 'kekaisaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('enjoyable', 'adjective', 'menyenangkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('entertaining', 'adjective', 'menghibur', 'B2', 'intermediate', ARRAY['oxford5000']),
('entrepreneur', 'noun', 'pengusaha', 'B2', 'intermediate', ARRAY['oxford5000']),
('envelope', 'noun', 'amplop', 'B2', 'intermediate', ARRAY['oxford5000']),
('equip', 'verb', 'melengkapi', 'B2', 'intermediate', ARRAY['oxford5000']),
('equivalent', 'noun', 'kesetaraan', 'B2', 'intermediate', ARRAY['oxford5000']),
('era', 'noun', 'era', 'B2', 'intermediate', ARRAY['oxford5000']),
('erupt', 'verb', 'meletus', 'B2', 'intermediate', ARRAY['oxford5000']),
('essentially', 'adverb', 'pada dasarnya', 'B2', 'intermediate', ARRAY['oxford5000']),
('ethic', 'noun', 'etika', 'B2', 'intermediate', ARRAY['oxford5000']),
('ethnic', 'adjective', 'etnis', 'B2', 'intermediate', ARRAY['oxford5000']),
('evaluation', 'noun', 'evaluasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('evident', 'adjective', 'jelas', 'B2', 'intermediate', ARRAY['oxford5000']),
('evolution', 'noun', 'evolusi', 'B2', 'intermediate', ARRAY['oxford5000']),
('evolve', 'verb', 'berkembang', 'B2', 'intermediate', ARRAY['oxford5000']),
('exceed', 'verb', 'melebihi', 'B2', 'intermediate', ARRAY['oxford5000']),
('exception', 'noun', 'pengecualian', 'B2', 'intermediate', ARRAY['oxford5000']),
('excessive', 'adjective', 'berlebihan', 'B2', 'intermediate', ARRAY['oxford5000']),
('exclude', 'verb', 'mengecualikan', 'B2', 'intermediate', ARRAY['oxford5000']),
('exotic', 'adjective', 'eksotis', 'B2', 'intermediate', ARRAY['oxford5000']),
('expansion', 'noun', 'ekspansi', 'B2', 'intermediate', ARRAY['oxford5000']),
('expertise', 'noun', 'keahlian', 'B2', 'intermediate', ARRAY['oxford5000']),
('exploit', 'verb', 'mengeksploitasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('exposure', 'noun', 'paparan', 'B2', 'intermediate', ARRAY['oxford5000']),
('extension', 'noun', 'perpanjangan', 'B2', 'intermediate', ARRAY['oxford5000']),
('extensive', 'adjective', 'luas', 'B2', 'intermediate', ARRAY['oxford5000']),
('extensively', 'adverb', 'secara luas', 'B2', 'intermediate', ARRAY['oxford5000']),
('fabric', 'noun', 'kain', 'B2', 'intermediate', ARRAY['oxford5000']),
('fabulous', 'adjective', 'luar biasa', 'B2', 'intermediate', ARRAY['oxford5000']),
('fake', 'adjective', 'palsu', 'B2', 'intermediate', ARRAY['oxford5000']),
('fame', 'noun', 'ketenaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('fantasy', 'noun', 'fantasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('fare', 'noun', 'ongkos', 'B2', 'intermediate', ARRAY['oxford5000']),
('federal', 'adjective', 'federal', 'B2', 'intermediate', ARRAY['oxford5000']),
('fever', 'noun', 'demam', 'B2', 'intermediate', ARRAY['oxford5000']),
('firefighter', 'noun', 'pemadam kebakaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('firework', 'noun', 'kembang api', 'B2', 'intermediate', ARRAY['oxford5000']),
('firm', 'adjective', 'tegas', 'B2', 'intermediate', ARRAY['oxford5000']),
('firmly', 'adverb', 'dengan tegas', 'B2', 'intermediate', ARRAY['oxford5000']),
('flavour', 'noun', 'rasa', 'B2', 'intermediate', ARRAY['oxford5000']),
('fond', 'adjective', 'menyukai', 'B2', 'intermediate', ARRAY['oxford5000']),
('forbid', 'verb', 'melarang', 'B2', 'intermediate', ARRAY['oxford5000']),
('forecast', 'noun', 'ramalan', 'B2', 'intermediate', ARRAY['oxford5000']),
('format', 'noun', 'format', 'B2', 'intermediate', ARRAY['oxford5000']),
('formation', 'noun', 'formasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('formerly', 'adverb', 'sebelumnya', 'B2', 'intermediate', ARRAY['oxford5000']),
('fortunate', 'adjective', 'beruntung', 'B2', 'intermediate', ARRAY['oxford5000']),
('forum', 'noun', 'forum', 'B2', 'intermediate', ARRAY['oxford5000']),
('fossil', 'noun', 'fosil', 'B2', 'intermediate', ARRAY['oxford5000']),
('foundation', 'noun', 'fondasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('founder', 'noun', 'pendiri', 'B2', 'intermediate', ARRAY['oxford5000']),
('fraction', 'noun', 'pecahan', 'B2', 'intermediate', ARRAY['oxford5000']),
('fragment', 'noun', 'fragmen', 'B2', 'intermediate', ARRAY['oxford5000']),
('framework', 'noun', 'kerangka', 'B2', 'intermediate', ARRAY['oxford5000']),
('fraud', 'noun', 'penipuan', 'B2', 'intermediate', ARRAY['oxford5000']),
('freely', 'adverb', 'secara bebas', 'B2', 'intermediate', ARRAY['oxford5000']),
('frequent', 'adjective', 'sering', 'B2', 'intermediate', ARRAY['oxford5000']),
('fulfil', 'verb', 'memenuhi', 'B2', 'intermediate', ARRAY['oxford5000']),
('fundamentally', 'adverb', 'secara mendasar', 'B2', 'intermediate', ARRAY['oxford5000']),
('furious', 'adjective', 'sangat marah', 'B2', 'intermediate', ARRAY['oxford5000']),
('gaming', 'noun', 'permainan', 'B2', 'intermediate', ARRAY['oxford5000']),
('gender', 'noun', 'jenis kelamin', 'B2', 'intermediate', ARRAY['oxford5000']),
('gene', 'noun', 'gen', 'B2', 'intermediate', ARRAY['oxford5000']),
('genetic', 'adjective', 'genetik', 'B2', 'intermediate', ARRAY['oxford5000']),
('genius', 'noun', 'jenius', 'B2', 'intermediate', ARRAY['oxford5000']),
('genuine', 'adjective', 'asli', 'B2', 'intermediate', ARRAY['oxford5000']),
('genuinely', 'adverb', 'dengan tulus', 'B2', 'intermediate', ARRAY['oxford5000']),
('gesture', 'noun', 'gerakan', 'B2', 'intermediate', ARRAY['oxford5000']),
('globalization', 'noun', 'globalisasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('globe', 'noun', 'bola dunia', 'B2', 'intermediate', ARRAY['oxford5000']),
('golden', 'adjective', 'berwarna emas', 'B2', 'intermediate', ARRAY['oxford5000']),
('gorgeous', 'adjective', 'sangat cantik', 'B2', 'intermediate', ARRAY['oxford5000']),
('governor', 'noun', 'gubernur', 'B2', 'intermediate', ARRAY['oxford5000']),
('greatly', 'adverb', 'dengan sangat', 'B2', 'intermediate', ARRAY['oxford5000']),
('greenhouse', 'noun', 'rumah kaca', 'B2', 'intermediate', ARRAY['oxford5000']),
('grocery', 'noun', 'toko bahan makanan', 'B2', 'intermediate', ARRAY['oxford5000']),
('guideline', 'noun', 'pedoman', 'B2', 'intermediate', ARRAY['oxford5000']),
('habitat', 'noun', 'habitat', 'B2', 'intermediate', ARRAY['oxford5000']),
('harbour', 'noun', 'pelabuhan', 'B2', 'intermediate', ARRAY['oxford5000']),
('headquarters', 'noun', 'markas besar', 'B2', 'intermediate', ARRAY['oxford5000']),
('heal', 'verb', 'menyembuhkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('healthcare', 'noun', 'layanan kesehatan', 'B2', 'intermediate', ARRAY['oxford5000']),
('helmet', 'noun', 'helm', 'B2', 'intermediate', ARRAY['oxford5000']),
('hence', 'adverb', 'oleh karena itu', 'B2', 'intermediate', ARRAY['oxford5000']),
('herb', 'noun', 'tanaman obat', 'B2', 'intermediate', ARRAY['oxford5000']),
('highway', 'noun', 'jalan raya', 'B2', 'intermediate', ARRAY['oxford5000']),
('hilarious', 'adjective', 'sangat lucu', 'B2', 'intermediate', ARRAY['oxford5000']),
('historian', 'noun', 'sejarawan', 'B2', 'intermediate', ARRAY['oxford5000']),
('homeless', 'adjective', 'tunawisma', 'B2', 'intermediate', ARRAY['oxford5000']),
('honesty', 'noun', 'kejujuran', 'B2', 'intermediate', ARRAY['oxford5000']),
('hopefully', 'adverb', 'semoga', 'B2', 'intermediate', ARRAY['oxford5000']),
('hunger', 'noun', 'kelaparan', 'B2', 'intermediate', ARRAY['oxford5000']),
('hypothesis', 'noun', 'hipotesis', 'B2', 'intermediate', ARRAY['oxford5000']),
('icon', 'noun', 'ikon', 'B2', 'intermediate', ARRAY['oxford5000']),
('identical', 'adjective', 'identik', 'B2', 'intermediate', ARRAY['oxford5000']),
('illusion', 'noun', 'ilusi', 'B2', 'intermediate', ARRAY['oxford5000']),
('immigration', 'noun', 'imigrasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('immune', 'adjective', 'kebal', 'B2', 'intermediate', ARRAY['oxford5000']),
('implement', 'verb', 'melaksanakan', 'B2', 'intermediate', ARRAY['oxford5000']),
('implication', 'noun', 'implikasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('incentive', 'noun', 'insentif', 'B2', 'intermediate', ARRAY['oxford5000']),
('incorporate', 'verb', 'menggabungkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('incorrect', 'adjective', 'tidak benar', 'B2', 'intermediate', ARRAY['oxford5000']),
('independence', 'noun', 'kemerdekaan', 'B2', 'intermediate', ARRAY['oxford5000']),
('indication', 'noun', 'indikasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('inevitable', 'adjective', 'tidak terhindarkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('inevitably', 'adverb', 'pasti terjadi', 'B2', 'intermediate', ARRAY['oxford5000']),
('infer', 'verb', 'menyimpulkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('inflation', 'noun', 'inflasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('infrastructure', 'noun', 'infrastruktur', 'B2', 'intermediate', ARRAY['oxford5000']),
('inhabitant', 'noun', 'penduduk', 'B2', 'intermediate', ARRAY['oxford5000']),
('inherit', 'verb', 'mewarisi', 'B2', 'intermediate', ARRAY['oxford5000']),
('innovation', 'noun', 'inovasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('innovative', 'adjective', 'inovatif', 'B2', 'intermediate', ARRAY['oxford5000']),
('input', 'noun', 'masukan', 'B2', 'intermediate', ARRAY['oxford5000']),
('inspector', 'noun', 'inspektur', 'B2', 'intermediate', ARRAY['oxford5000']),
('installation', 'noun', 'instalasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('instant', 'adjective', 'seketika', 'B2', 'intermediate', ARRAY['oxford5000']),
('instantly', 'adverb', 'segera', 'B2', 'intermediate', ARRAY['oxford5000']),
('integrate', 'verb', 'mengintegrasikan', 'B2', 'intermediate', ARRAY['oxford5000']),
('interact', 'verb', 'berinteraksi', 'B2', 'intermediate', ARRAY['oxford5000']),
('interaction', 'noun', 'interaksi', 'B2', 'intermediate', ARRAY['oxford5000']),
('interpretation', 'noun', 'interpretasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('interval', 'noun', 'jeda', 'B2', 'intermediate', ARRAY['oxford5000']),
('invade', 'verb', 'menyerbu', 'B2', 'intermediate', ARRAY['oxford5000']),
('invasion', 'noun', 'invasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('investor', 'noun', 'investor', 'B2', 'intermediate', ARRAY['oxford5000']),
('isolate', 'verb', 'mengisolasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('isolated', 'adjective', 'terpencil', 'B2', 'intermediate', ARRAY['oxford5000']),
('journalism', 'noun', 'jurnalisme', 'B2', 'intermediate', ARRAY['oxford5000']),
('lately', 'adverb', 'belakangan ini', 'B2', 'intermediate', ARRAY['oxford5000']),
('legend', 'noun', 'legenda', 'B2', 'intermediate', ARRAY['oxford5000']),
('lifetime', 'noun', 'seumur hidup', 'B2', 'intermediate', ARRAY['oxford5000']),
('limitation', 'noun', 'keterbatasan', 'B2', 'intermediate', ARRAY['oxford5000']),
('literally', 'adverb', 'secara harfiah', 'B2', 'intermediate', ARRAY['oxford5000']),
('logo', 'noun', 'logo', 'B2', 'intermediate', ARRAY['oxford5000']),
('lottery', 'noun', 'undian', 'B2', 'intermediate', ARRAY['oxford5000']),
('loyal', 'adjective', 'setia', 'B2', 'intermediate', ARRAY['oxford5000']),
('lyric', 'noun', 'lirik', 'B2', 'intermediate', ARRAY['oxford5000']),
('magnificent', 'adjective', 'megah', 'B2', 'intermediate', ARRAY['oxford5000']),
('manufacture', 'verb', 'memproduksi', 'B2', 'intermediate', ARRAY['oxford5000']),
('marathon', 'noun', 'maraton', 'B2', 'intermediate', ARRAY['oxford5000']),
('martial', 'adjective', 'berhubungan dengan militer', 'B2', 'intermediate', ARRAY['oxford5000']),
('mayor', 'noun', 'walikota', 'B2', 'intermediate', ARRAY['oxford5000']),
('mechanic', 'noun', 'montir', 'B2', 'intermediate', ARRAY['oxford5000']),
('mechanical', 'adjective', 'mekanis', 'B2', 'intermediate', ARRAY['oxford5000']),
('mechanism', 'noun', 'mekanisme', 'B2', 'intermediate', ARRAY['oxford5000']),
('medal', 'noun', 'medali', 'B2', 'intermediate', ARRAY['oxford5000']),
('medication', 'noun', 'pengobatan', 'B2', 'intermediate', ARRAY['oxford5000']),
('membership', 'noun', 'keanggotaan', 'B2', 'intermediate', ARRAY['oxford5000']),
('memorable', 'adjective', 'berkesan', 'B2', 'intermediate', ARRAY['oxford5000']),
('metaphor', 'noun', 'metafora', 'B2', 'intermediate', ARRAY['oxford5000']),
('miner', 'noun', 'penambang', 'B2', 'intermediate', ARRAY['oxford5000']),
('miserable', 'adjective', 'sengsara', 'B2', 'intermediate', ARRAY['oxford5000']),
('modest', 'adjective', 'sederhana', 'B2', 'intermediate', ARRAY['oxford5000']),
('monument', 'noun', 'monumen', 'B2', 'intermediate', ARRAY['oxford5000']),
('moreover', 'adverb', 'terlebih lagi', 'B2', 'intermediate', ARRAY['oxford5000']),
('mortgage', 'noun', 'hipotek', 'B2', 'intermediate', ARRAY['oxford5000']),
('mosque', 'noun', 'masjid', 'B2', 'intermediate', ARRAY['oxford5000']),
('motivate', 'verb', 'memotivasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('motivation', 'noun', 'motivasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('myth', 'noun', 'mitos', 'B2', 'intermediate', ARRAY['oxford5000']),
('navigation', 'noun', 'navigasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('necessity', 'noun', 'kebutuhan', 'B2', 'intermediate', ARRAY['oxford5000']),
('negotiate', 'verb', 'bernegosiasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('negotiation', 'noun', 'negosiasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('neutral', 'adjective', 'netral', 'B2', 'intermediate', ARRAY['oxford5000']),
('norm', 'noun', 'norma', 'B2', 'intermediate', ARRAY['oxford5000']),
('novelist', 'noun', 'novelis', 'B2', 'intermediate', ARRAY['oxford5000']),
('nowadays', 'adverb', 'zaman sekarang', 'B2', 'intermediate', ARRAY['oxford5000']),
('nutrition', 'noun', 'nutrisi', 'B2', 'intermediate', ARRAY['oxford5000']),
('obesity', 'noun', 'obesitas', 'B2', 'intermediate', ARRAY['oxford5000']),
('observer', 'noun', 'pengamat', 'B2', 'intermediate', ARRAY['oxford5000']),
('obstacle', 'noun', 'hambatan', 'B2', 'intermediate', ARRAY['oxford5000']),
('occupation', 'noun', 'pekerjaan', 'B2', 'intermediate', ARRAY['oxford5000']),
('offender', 'noun', 'pelanggar', 'B2', 'intermediate', ARRAY['oxford5000']),
('ongoing', 'adjective', 'sedang berlangsung', 'B2', 'intermediate', ARRAY['oxford5000']),
('openly', 'adverb', 'secara terbuka', 'B2', 'intermediate', ARRAY['oxford5000']),
('opera', 'noun', 'opera', 'B2', 'intermediate', ARRAY['oxford5000']),
('operator', 'noun', 'operator', 'B2', 'intermediate', ARRAY['oxford5000']),
('optimistic', 'adjective', 'optimistis', 'B2', 'intermediate', ARRAY['oxford5000']),
('orchestra', 'noun', 'orkestra', 'B2', 'intermediate', ARRAY['oxford5000']),
('organic', 'adjective', 'organik', 'B2', 'intermediate', ARRAY['oxford5000']),
('outfit', 'noun', 'pakaian', 'B2', 'intermediate', ARRAY['oxford5000']),
('output', 'noun', 'hasil keluaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('outstanding', 'adjective', 'luar biasa', 'B2', 'intermediate', ARRAY['oxford5000']),
('overcome', 'verb', 'mengatasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('overseas', 'adverb', 'di luar negeri', 'B2', 'intermediate', ARRAY['oxford5000']),
('ownership', 'noun', 'kepemilikan', 'B2', 'intermediate', ARRAY['oxford5000']),
('oxygen', 'noun', 'oksigen', 'B2', 'intermediate', ARRAY['oxford5000']),
('panic', 'noun', 'panik', 'B2', 'intermediate', ARRAY['oxford5000']),
('participation', 'noun', 'partisipasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('partnership', 'noun', 'kemitraan', 'B2', 'intermediate', ARRAY['oxford5000']),
('passionate', 'adjective', 'penuh gairah', 'B2', 'intermediate', ARRAY['oxford5000']),
('password', 'noun', 'kata sandi', 'B2', 'intermediate', ARRAY['oxford5000']),
('patience', 'noun', 'kesabaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('peer', 'noun', 'rekan', 'B2', 'intermediate', ARRAY['oxford5000']),
('penalty', 'noun', 'hukuman', 'B2', 'intermediate', ARRAY['oxford5000']),
('perceive', 'verb', 'memahami', 'B2', 'intermediate', ARRAY['oxford5000']),
('perception', 'noun', 'persepsi', 'B2', 'intermediate', ARRAY['oxford5000']),
('permanently', 'adverb', 'secara permanen', 'B2', 'intermediate', ARRAY['oxford5000']),
('pill', 'noun', 'pil', 'B2', 'intermediate', ARRAY['oxford5000']),
('placement', 'noun', 'penempatan', 'B2', 'intermediate', ARRAY['oxford5000']),
('portion', 'noun', 'porsi', 'B2', 'intermediate', ARRAY['oxford5000']),
('potentially', 'adverb', 'berpotensi', 'B2', 'intermediate', ARRAY['oxford5000']),
('precious', 'adjective', 'berharga', 'B2', 'intermediate', ARRAY['oxford5000']),
('precise', 'adjective', 'tepat', 'B2', 'intermediate', ARRAY['oxford5000']),
('precisely', 'adverb', 'dengan tepat', 'B2', 'intermediate', ARRAY['oxford5000']),
('preference', 'noun', 'preferensi', 'B2', 'intermediate', ARRAY['oxford5000']),
('pride', 'noun', 'kebanggaan', 'B2', 'intermediate', ARRAY['oxford5000']),
('primarily', 'adverb', 'terutama', 'B2', 'intermediate', ARRAY['oxford5000']),
('probability', 'noun', 'kemungkinan', 'B2', 'intermediate', ARRAY['oxford5000']),
('programming', 'noun', 'pemrograman', 'B2', 'intermediate', ARRAY['oxford5000']),
('prohibit', 'verb', 'melarang', 'B2', 'intermediate', ARRAY['oxford5000']),
('promising', 'adjective', 'menjanjikan', 'B2', 'intermediate', ARRAY['oxford5000']),
('promotion', 'noun', 'promosi', 'B2', 'intermediate', ARRAY['oxford5000']),
('proportion', 'noun', 'proporsi', 'B2', 'intermediate', ARRAY['oxford5000']),
('protein', 'noun', 'protein', 'B2', 'intermediate', ARRAY['oxford5000']),
('psychological', 'adjective', 'psikologis', 'B2', 'intermediate', ARRAY['oxford5000']),
('publicity', 'noun', 'publisitas', 'B2', 'intermediate', ARRAY['oxford5000']),
('purely', 'adverb', 'murni', 'B2', 'intermediate', ARRAY['oxford5000']),
('pursuit', 'noun', 'pengejaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('questionnaire', 'noun', 'kuesioner', 'B2', 'intermediate', ARRAY['oxford5000']),
('racial', 'adjective', 'rasial', 'B2', 'intermediate', ARRAY['oxford5000']),
('racism', 'noun', 'rasisme', 'B2', 'intermediate', ARRAY['oxford5000']),
('radiation', 'noun', 'radiasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('random', 'adjective', 'acak', 'B2', 'intermediate', ARRAY['oxford5000']),
('rating', 'noun', 'peringkat', 'B2', 'intermediate', ARRAY['oxford5000']),
('reasonably', 'adverb', 'secara wajar', 'B2', 'intermediate', ARRAY['oxford5000']),
('rebuild', 'verb', 'membangun kembali', 'B2', 'intermediate', ARRAY['oxford5000']),
('recession', 'noun', 'resesi', 'B2', 'intermediate', ARRAY['oxford5000']),
('recognition', 'noun', 'pengakuan', 'B2', 'intermediate', ARRAY['oxford5000']),
('recovery', 'noun', 'pemulihan', 'B2', 'intermediate', ARRAY['oxford5000']),
('recruitment', 'noun', 'perekrutan', 'B2', 'intermediate', ARRAY['oxford5000']),
('refugee', 'noun', 'pengungsi', 'B2', 'intermediate', ARRAY['oxford5000']),
('registration', 'noun', 'pendaftaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('regulate', 'verb', 'mengatur', 'B2', 'intermediate', ARRAY['oxford5000']),
('reinforce', 'verb', 'memperkuat', 'B2', 'intermediate', ARRAY['oxford5000']),
('relieve', 'verb', 'meringankan', 'B2', 'intermediate', ARRAY['oxford5000']),
('remarkable', 'adjective', 'luar biasa', 'B2', 'intermediate', ARRAY['oxford5000']),
('remarkably', 'adverb', 'dengan luar biasa', 'B2', 'intermediate', ARRAY['oxford5000']),
('resign', 'verb', 'mengundurkan diri', 'B2', 'intermediate', ARRAY['oxford5000']),
('resolution', 'noun', 'resolusi', 'B2', 'intermediate', ARRAY['oxford5000']),
('restore', 'verb', 'memulihkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('restrict', 'verb', 'membatasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('restriction', 'noun', 'pembatasan', 'B2', 'intermediate', ARRAY['oxford5000']),
('retirement', 'noun', 'pensiun', 'B2', 'intermediate', ARRAY['oxford5000']),
('revenue', 'noun', 'pendapatan', 'B2', 'intermediate', ARRAY['oxford5000']),
('ridiculous', 'adjective', 'konyol', 'B2', 'intermediate', ARRAY['oxford5000']),
('risky', 'adjective', 'berisiko', 'B2', 'intermediate', ARRAY['oxford5000']),
('rival', 'noun', 'saingan', 'B2', 'intermediate', ARRAY['oxford5000']),
('robbery', 'noun', 'perampokan', 'B2', 'intermediate', ARRAY['oxford5000']),
('romance', 'noun', 'percintaan', 'B2', 'intermediate', ARRAY['oxford5000']),
('roughly', 'adverb', 'kira-kira', 'B2', 'intermediate', ARRAY['oxford5000']),
('satisfaction', 'noun', 'kepuasan', 'B2', 'intermediate', ARRAY['oxford5000']),
('scandal', 'noun', 'skandal', 'B2', 'intermediate', ARRAY['oxford5000']),
('scenario', 'noun', 'skenario', 'B2', 'intermediate', ARRAY['oxford5000']),
('scholar', 'noun', 'cendekiawan', 'B2', 'intermediate', ARRAY['oxford5000']),
('scholarship', 'noun', 'beasiswa', 'B2', 'intermediate', ARRAY['oxford5000']),
('seminar', 'noun', 'seminar', 'B2', 'intermediate', ARRAY['oxford5000']),
('severely', 'adverb', 'dengan parah', 'B2', 'intermediate', ARRAY['oxford5000']),
('shortage', 'noun', 'kekurangan', 'B2', 'intermediate', ARRAY['oxford5000']),
('sibling', 'noun', 'saudara kandung', 'B2', 'intermediate', ARRAY['oxford5000']),
('significance', 'noun', 'arti penting', 'B2', 'intermediate', ARRAY['oxford5000']),
('skilled', 'adjective', 'terampil', 'B2', 'intermediate', ARRAY['oxford5000']),
('slogan', 'noun', 'slogan', 'B2', 'intermediate', ARRAY['oxford5000']),
('sophisticated', 'adjective', 'canggih', 'B2', 'intermediate', ARRAY['oxford5000']),
('specialize', 'verb', 'mengkhususkan diri', 'B2', 'intermediate', ARRAY['oxford5000']),
('spectacular', 'adjective', 'spektakuler', 'B2', 'intermediate', ARRAY['oxford5000']),
('spectator', 'noun', 'penonton', 'B2', 'intermediate', ARRAY['oxford5000']),
('speculate', 'verb', 'berspekulasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('speculation', 'noun', 'spekulasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('spice', 'noun', 'rempah-rempah', 'B2', 'intermediate', ARRAY['oxford5000']),
('sponsorship', 'noun', 'sponsor', 'B2', 'intermediate', ARRAY['oxford5000']),
('stance', 'noun', 'sikap', 'B2', 'intermediate', ARRAY['oxford5000']),
('starve', 'verb', 'kelaparan', 'B2', 'intermediate', ARRAY['oxford5000']),
('steadily', 'adverb', 'dengan stabil', 'B2', 'intermediate', ARRAY['oxford5000']),
('steam', 'noun', 'uap', 'B2', 'intermediate', ARRAY['oxford5000']),
('stimulate', 'verb', 'merangsang', 'B2', 'intermediate', ARRAY['oxford5000']),
('strengthen', 'verb', 'memperkuat', 'B2', 'intermediate', ARRAY['oxford5000']),
('strictly', 'adverb', 'dengan ketat', 'B2', 'intermediate', ARRAY['oxford5000']),
('stunning', 'adjective', 'memukau', 'B2', 'intermediate', ARRAY['oxford5000']),
('suburb', 'noun', 'daerah pinggiran kota', 'B2', 'intermediate', ARRAY['oxford5000']),
('sufficient', 'adjective', 'cukup', 'B2', 'intermediate', ARRAY['oxford5000']),
('sufficiently', 'adverb', 'dengan cukup', 'B2', 'intermediate', ARRAY['oxford5000']),
('surgeon', 'noun', 'ahli bedah', 'B2', 'intermediate', ARRAY['oxford5000']),
('survival', 'noun', 'kelangsungan hidup', 'B2', 'intermediate', ARRAY['oxford5000']),
('survivor', 'noun', 'penyintas', 'B2', 'intermediate', ARRAY['oxford5000']),
('suspend', 'verb', 'menangguhkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('sustainable', 'adjective', 'berkelanjutan', 'B2', 'intermediate', ARRAY['oxford5000']),
('sympathetic', 'adjective', 'simpatik', 'B2', 'intermediate', ARRAY['oxford5000']),
('technological', 'adjective', 'berhubungan dengan teknologi', 'B2', 'intermediate', ARRAY['oxford5000']),
('tendency', 'noun', 'kecenderungan', 'B2', 'intermediate', ARRAY['oxford5000']),
('tension', 'noun', 'ketegangan', 'B2', 'intermediate', ARRAY['oxford5000']),
('terrorism', 'noun', 'terorisme', 'B2', 'intermediate', ARRAY['oxford5000']),
('terrorist', 'noun', 'teroris', 'B2', 'intermediate', ARRAY['oxford5000']),
('textbook', 'noun', 'buku pelajaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('theft', 'noun', 'pencurian', 'B2', 'intermediate', ARRAY['oxford5000']),
('therapist', 'noun', 'terapis', 'B2', 'intermediate', ARRAY['oxford5000']),
('thesis', 'noun', 'tesis', 'B2', 'intermediate', ARRAY['oxford5000']),
('thorough', 'adjective', 'menyeluruh', 'B2', 'intermediate', ARRAY['oxford5000']),
('thoroughly', 'adverb', 'secara menyeluruh', 'B2', 'intermediate', ARRAY['oxford5000']),
('timing', 'noun', 'waktu pelaksanaan', 'B2', 'intermediate', ARRAY['oxford5000']),
('tournament', 'noun', 'turnamen', 'B2', 'intermediate', ARRAY['oxford5000']),
('tragedy', 'noun', 'tragedi', 'B2', 'intermediate', ARRAY['oxford5000']),
('tragic', 'adjective', 'tragis', 'B2', 'intermediate', ARRAY['oxford5000']),
('trait', 'noun', 'sifat', 'B2', 'intermediate', ARRAY['oxford5000']),
('transmit', 'verb', 'menularkan', 'B2', 'intermediate', ARRAY['oxford5000']),
('transportation', 'noun', 'transportasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('treasure', 'noun', 'harta karun', 'B2', 'intermediate', ARRAY['oxford5000']),
('tribe', 'noun', 'suku', 'B2', 'intermediate', ARRAY['oxford5000']),
('trigger', 'verb', 'memicu', 'B2', 'intermediate', ARRAY['oxford5000']),
('troop', 'noun', 'pasukan', 'B2', 'intermediate', ARRAY['oxford5000']),
('uncertainty', 'noun', 'ketidakpastian', 'B2', 'intermediate', ARRAY['oxford5000']),
('undergo', 'verb', 'menjalani', 'B2', 'intermediate', ARRAY['oxford5000']),
('undertake', 'verb', 'melakukan', 'B2', 'intermediate', ARRAY['oxford5000']),
('unite', 'verb', 'menyatukan', 'B2', 'intermediate', ARRAY['oxford5000']),
('unity', 'noun', 'persatuan', 'B2', 'intermediate', ARRAY['oxford5000']),
('universal', 'adjective', 'universal', 'B2', 'intermediate', ARRAY['oxford5000']),
('urgent', 'adjective', 'mendesak', 'B2', 'intermediate', ARRAY['oxford5000']),
('usage', 'noun', 'penggunaan', 'B2', 'intermediate', ARRAY['oxford5000']),
('valid', 'adjective', 'berlaku', 'B2', 'intermediate', ARRAY['oxford5000']),
('variation', 'noun', 'variasi', 'B2', 'intermediate', ARRAY['oxford5000']),
('viewpoint', 'noun', 'sudut pandang', 'B2', 'intermediate', ARRAY['oxford5000']),
('visa', 'noun', 'visa', 'B2', 'intermediate', ARRAY['oxford5000']),
('voluntary', 'adjective', 'sukarela', 'B2', 'intermediate', ARRAY['oxford5000']),
('wander', 'verb', 'berkeliaran', 'B2', 'intermediate', ARRAY['oxford5000']),
('welfare', 'noun', 'kesejahteraan', 'B2', 'intermediate', ARRAY['oxford5000']),
('wheat', 'noun', 'gandum', 'B2', 'intermediate', ARRAY['oxford5000']),
('widespread', 'adjective', 'tersebar luas', 'B2', 'intermediate', ARRAY['oxford5000']),
('wisdom', 'noun', 'kebijaksanaan', 'B2', 'intermediate', ARRAY['oxford5000']),
('withdraw', 'verb', 'menarik diri', 'B2', 'intermediate', ARRAY['oxford5000']),
('workforce', 'noun', 'tenaga kerja', 'B2', 'intermediate', ARRAY['oxford5000']),
('workplace', 'noun', 'tempat kerja', 'B2', 'intermediate', ARRAY['oxford5000']),
('workshop', 'noun', 'lokakarya', 'B2', 'intermediate', ARRAY['oxford5000']),
('wrist', 'noun', 'pergelangan tangan', 'B2', 'intermediate', ARRAY['oxford5000'])
ON CONFLICT (word) DO NOTHING;
